<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_This field is required</name>
   <tag></tag>
   <elementGuidId>7df4ea29-b587-479d-bf73-06f791febf3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email_pjteknis_pentest-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='email_pjteknis_pentest-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>21ecd8de-f23d-4173-9d34-2e7777c4b8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_pjteknis_pentest-error</value>
      <webElementGuid>e23c5a37-0088-42a1-afa3-3452618680bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>a48f0986-4342-4442-9e10-e12154a0944c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>email_pjteknis_pentest</value>
      <webElementGuid>72aaaaff-ea30-4d23-b283-0d9f34416589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>816f2a2e-b9f8-456e-a64a-b3e7d5574066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_pjteknis_pentest-error&quot;)</value>
      <webElementGuid>67c77571-c905-4b3b-a10f-b91599d7b895</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='email_pjteknis_pentest-error']</value>
      <webElementGuid>1360b645-704d-43c5-9bb9-726258e13485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[5]/div[2]/div[5]/label[2]</value>
      <webElementGuid>fbe77ca0-0fb7-4f18-b3a5-c1115b7e7449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label[2]</value>
      <webElementGuid>0f47ddfe-2fa2-4117-975a-2e6a6f1071c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'email_pjteknis_pentest-error' and (text() = 'This field is required.' or . = 'This field is required.')]</value>
      <webElementGuid>649995b9-aee6-4337-bc87-abb624a9729a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
