<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Data Form</name>
   <tag></tag>
   <elementGuidId>bec83969-dbc4-4255-9700-a972a91e3672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-tambah-form']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-tambah-form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32cb5b34-0928-44b4-8d04-56af04dc3d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bad60460-5d9a-433d-920b-8ff8934f5ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-tambah-form</value>
      <webElementGuid>63144f88-d09d-4fa5-b864-ed0476b8a810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>6281807f-cb80-43e5-b74b-2354dc4e7ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Data Form</value>
      <webElementGuid>631c2aef-dc9d-4bb3-9839-178d10b24f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-tambah-form&quot;)</value>
      <webElementGuid>1ada5de7-e02d-4106-8e57-b0538c74f00f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-tambah-form']</value>
      <webElementGuid>437718f9-39a3-41e8-84a6-829df808ffaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div/center/button</value>
      <webElementGuid>4ad17b46-2e8b-43c8-898f-509b6dde8835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/button</value>
      <webElementGuid>9fea631d-d2fe-4955-9a06-fe30a622dc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn-tambah-form' and (text() = 'Tambah Data Form' or . = 'Tambah Data Form')]</value>
      <webElementGuid>69360888-2799-40f3-8543-b4d304e533f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
