<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_slot_memory</name>
   <tag></tag>
   <elementGuidId>48d84e8e-6293-4391-bad9-ed6bafcd080a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='slot_memory']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slot_memory</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b01e3d30-ae25-4734-9459-bd9610681400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0d74c6cd-f13a-47b2-8ab9-46046205ada9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>slot_memory</value>
      <webElementGuid>eaa54f6d-c16c-47d6-b3c6-48a60e8bcc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c7b8b8a7-149a-408c-82aa-460c4cf3e6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Slot Memory</value>
      <webElementGuid>094b768a-cb8b-41d5-a87f-60604b059446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slot_memory</value>
      <webElementGuid>e89ec6c0-0974-4af0-8859-cc1080e7915e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slot_memory&quot;)</value>
      <webElementGuid>e9db8c9d-96f5-4a4e-b3d9-ea54d16c344f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='slot_memory']</value>
      <webElementGuid>d056ef52-dc17-4211-af37-5d98193dd23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[4]/div[4]/div[2]/input</value>
      <webElementGuid>2b709eb0-19eb-44cd-a767-60aabe1e476f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>e059265e-ce2b-49a9-965c-e14487c3bdaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'slot_memory' and @placeholder = 'Slot Memory' and @id = 'slot_memory']</value>
      <webElementGuid>b8529a3c-05ff-49d3-82a8-6455e0cd8507</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
