<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_memory</name>
   <tag></tag>
   <elementGuidId>a1dd08ec-4d5b-42f4-8ca9-cdfb672d7096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='memory[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;memory[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a900070-4eeb-4668-a492-6c95051ae503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ac82812c-9545-4c98-b11d-89e191ad0191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>memory[]</value>
      <webElementGuid>a09f46a5-4920-4bc6-93ec-76602ccc2ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-9 col-sm-9 col-xs-9</value>
      <webElementGuid>42adde77-b108-4abc-9a48-1003bbc82182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Kapasitas Memory Server Virtual</value>
      <webElementGuid>2f8cb185-735a-42ac-a31e-e99f9738c2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insert-form&quot;)/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control col-md-9 col-sm-9 col-xs-9&quot;]</value>
      <webElementGuid>24669408-4816-4abb-a120-233911f830e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='memory[]']</value>
      <webElementGuid>85cebd2f-e7d9-4792-82f7-02f5c0a19570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insert-form']/div[2]/div[4]/input</value>
      <webElementGuid>3da5bf5d-a4ab-43f2-95f3-34129e3175f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/input</value>
      <webElementGuid>f0133ffc-9e26-4e39-8dfd-41d913821875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'memory[]' and @placeholder = 'Masukkan Kapasitas Memory Server Virtual']</value>
      <webElementGuid>eb8d5541-850f-4eec-8f4d-b127ec9ff8b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
