<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_serial_number</name>
   <tag></tag>
   <elementGuidId>4c4cb9e7-2c3b-4188-aa0b-4fb5357ca488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04f67726-5106-48b8-b108-ea1f7d0026f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>03a52b5c-aa1e-4c3c-8f40-3a54a8dfeae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serial_number</value>
      <webElementGuid>79eaeecb-8e3d-43a2-9120-d25dd47ae545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>be8b2923-f825-4ab0-afd6-624bd11391b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Serial Number Server</value>
      <webElementGuid>cd4a87ec-7245-4b51-87bb-2c97b4962b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sn</value>
      <webElementGuid>183dbe71-c08d-4336-a9c8-779ab9c6050c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sn&quot;)</value>
      <webElementGuid>57e7cff5-8644-4d8c-b53a-51af6b3e614a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sn']</value>
      <webElementGuid>07c25037-daff-4e60-9a6f-c2358e5df1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[3]/div/input</value>
      <webElementGuid>3f70fb93-fba8-40b3-9b22-6772264e1cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>4d655812-e7d9-4540-b5e4-af42f133a998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'serial_number' and @placeholder = 'Serial Number Server' and @id = 'sn']</value>
      <webElementGuid>725b0cb0-2ff0-4d71-8c5d-6d317ec595c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
