<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_operating_system_virtual</name>
   <tag></tag>
   <elementGuidId>4608ab94-5a68-4942-bbec-8d37c37a90b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='operating_system_virtual[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;operating_system_virtual[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55c1a4ae-fb85-4df3-9f12-b51a66f99fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4005f904-badc-43ee-8c53-720717ce962b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>operating_system_virtual[]</value>
      <webElementGuid>65f808f7-71a5-4f97-aa97-96a0953e914e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>706250e4-e7e9-4f99-8889-b893249ba80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan OS Server Virtual</value>
      <webElementGuid>81ab2cef-1475-47e0-a092-1a34c8d6c4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insert-form&quot;)/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>818dbc3f-e810-43a7-ac54-e3cc92fd46d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='operating_system_virtual[]']</value>
      <webElementGuid>57596978-29c7-4d90-a076-030da6a0ff37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insert-form']/div[3]/div/input</value>
      <webElementGuid>cfbd6b6b-2b30-4218-be3c-2a97c0970b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>cc819bd9-d473-41cb-b54a-228cf86a5473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'operating_system_virtual[]' and @placeholder = 'Masukkan OS Server Virtual']</value>
      <webElementGuid>963d91ea-d17a-4cce-a8dc-274f4d44f983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
