<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_kapasitas_hdd</name>
   <tag></tag>
   <elementGuidId>3aedbfd9-2547-47c2-9ad8-8d7f5b32abc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kapasitas_hdd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kapasitas_hdd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57684294-646f-4c57-a801-5d7d4024157e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e7dbe744-63a6-4e3d-8ab7-3d0c89b2dd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kapasitas_hdd</value>
      <webElementGuid>76d82483-12ba-43d9-b132-ea25ee5239dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-9 col-sm-9 col-xs-9</value>
      <webElementGuid>f99e57c4-bb7d-4571-835d-71a5b5e39a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kapasitas</value>
      <webElementGuid>ccd962f1-2939-4f24-ace9-d941a18945cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kapasitas_hdd</value>
      <webElementGuid>7a7c5e7e-0dc0-4763-be25-1a961604e593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kapasitas_hdd&quot;)</value>
      <webElementGuid>baf7d0fe-5e60-486b-9ceb-7cd48f89824a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kapasitas_hdd']</value>
      <webElementGuid>fc923bdd-4e2e-473f-a117-479634545ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[4]/div[3]/div[4]/input</value>
      <webElementGuid>702cef98-d1d4-42ce-bc1f-3dede58167c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[4]/input</value>
      <webElementGuid>82498ae3-ca2f-4faa-8a0a-5c0ddafe1f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'kapasitas_hdd' and @placeholder = 'Kapasitas' and @id = 'kapasitas_hdd']</value>
      <webElementGuid>8009b159-7737-499d-b649-97e24745ac74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
