<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_jumlah_memory</name>
   <tag></tag>
   <elementGuidId>82ce517e-1436-47c8-a2bd-734de45faaed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jml_memory']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jml_memory</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e0fef05-6896-42b8-9b5f-b1c8190ba989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ddd37f38-606a-4ed0-a7f5-f8c7e1790f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah_memory</value>
      <webElementGuid>ae471267-4195-4813-b684-f14b6a489dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>92cceb44-2229-48d6-8f2b-e30694daeccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah Memory</value>
      <webElementGuid>6d8d08a8-7b90-47c2-a632-3a306aa08fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jml_memory</value>
      <webElementGuid>2ecfa5f5-95d2-43d5-bd8d-ed57104190bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jml_memory&quot;)</value>
      <webElementGuid>b7d0e871-ede4-4840-8907-411e81ceef82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jml_memory']</value>
      <webElementGuid>0e5a8a9f-3e76-44b8-b577-ed2c42dc9f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[4]/div[4]/div[3]/input</value>
      <webElementGuid>6444e08f-3ad6-4551-bc5d-5bf022b76bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/input</value>
      <webElementGuid>57e4fd73-bd9e-40bb-ac94-caba420768a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'jumlah_memory' and @placeholder = 'Jumlah Memory' and @id = 'jml_memory']</value>
      <webElementGuid>dcb02630-7caf-4d71-9d0e-aabd256c7ee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
