<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_slot_hdd</name>
   <tag></tag>
   <elementGuidId>e43976c8-b322-43d5-8fd3-30fe03723a18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='slot_hdd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slot_hdd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>944db849-e6bb-4b03-96c7-b447220051ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c2bbe18f-8f90-4a5c-9f32-498bfd11b319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>slot_hdd</value>
      <webElementGuid>068c43dc-1ee4-4ada-8e94-f581320450e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c96c8bb1-0fe0-4d5b-b75d-59b3a5278e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Slot Hardisk</value>
      <webElementGuid>9e4966a7-4b34-4566-8c92-4cac1c060a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slot_hdd</value>
      <webElementGuid>200c2e8d-4692-4f28-a8c1-93d16754aaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slot_hdd&quot;)</value>
      <webElementGuid>15425423-ee4d-4cd1-a500-162f3a6e3396</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='slot_hdd']</value>
      <webElementGuid>062ef946-e22f-4893-b2e7-da17e3891580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[4]/div[3]/div[2]/input</value>
      <webElementGuid>bdddf93f-e691-4ef5-9ada-afee4bc9356e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[2]/input</value>
      <webElementGuid>d61cbbcc-acb7-4c2a-9c1c-8fb799bee294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'slot_hdd' and @placeholder = 'Slot Hardisk' and @id = 'slot_hdd']</value>
      <webElementGuid>573d16a2-fd69-4c5c-9298-096836e03c0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
