<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjteknis_jabatan</name>
   <tag></tag>
   <elementGuidId>771c5af2-289f-4f21-ae00-203681cdc5a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jpjt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jpjt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dcd87ad-73b9-43b3-a867-82a0ef2e53da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>445e405f-2e97-4702-b782-baac433ff473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>25a6a897-7f49-427d-9c2d-063964ad1b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjteknis_jabatan</value>
      <webElementGuid>5bfb79f4-1c04-457f-8242-3ae42f05dfdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Jabatan Penanggung Jawab Teknis</value>
      <webElementGuid>0a26104d-9789-4d39-a43f-e7fc2e37a70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jpjt</value>
      <webElementGuid>36ca6c89-a2d0-4fb3-b425-0865a8663006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jpjt&quot;)</value>
      <webElementGuid>aff65a00-7d55-4aa4-b79d-077e675cbf03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jpjt']</value>
      <webElementGuid>a4cf7ab4-5d76-45bd-b21b-31d290124ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form4']/div/div[4]/input</value>
      <webElementGuid>371903c5-d342-46b8-8eba-f824b63d1f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/div[4]/input</value>
      <webElementGuid>1604df0b-11ca-407f-84c5-0dd6ad70418b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjteknis_jabatan' and @placeholder = 'Masukkan Jabatan Penanggung Jawab Teknis' and @id = 'jpjt']</value>
      <webElementGuid>de1b4ad5-9308-41da-aaf9-058997876528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
