<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tgl_pembelian</name>
   <tag></tag>
   <elementGuidId>a32ae3c0-2d48-4e24-a243-c138758d1a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tgl_beli']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tgl_beli</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a1ea41e-06d0-4c98-9885-86968ff4e400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f16785e-c34c-4934-a8de-8cd179001cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7c726308-6d7c-4a2e-8aa7-7db8d5739811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_pembelian </value>
      <webElementGuid>6b79f7ae-b1c7-4a94-9d26-39c548b7d031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Tanggal Pembelian Server</value>
      <webElementGuid>ea91b394-b961-43a4-a682-94d42571ab66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tgl_beli</value>
      <webElementGuid>81a6d7ee-e36c-4a5c-ba0c-fae2fb60ba42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tgl_beli&quot;)</value>
      <webElementGuid>e0b9d384-026b-4145-bd07-00b39b39a983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tgl_beli']</value>
      <webElementGuid>a24b83ed-4973-445a-82ee-07bdada39819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data_1']/div/input</value>
      <webElementGuid>e7c3374c-2486-407c-8bac-cf6586c5952c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/input</value>
      <webElementGuid>4dc255f1-359f-4b74-bcbb-efbaabe4ade9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tgl_pembelian ' and @placeholder = 'Masukkan Tanggal Pembelian Server' and @id = 'tgl_beli']</value>
      <webElementGuid>02a468ec-2742-4caa-a55e-b9ebb3ed4ab5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
