<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_kapasitas_memory</name>
   <tag></tag>
   <elementGuidId>ff398018-ab4e-48b4-90ea-8f0eb77c7930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kapasitas_memory']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kapasitas_memory</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f32bc9c7-931a-4c79-8198-e2ff29209174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>23cf171d-2d55-44a1-9ec3-194a18978c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kapasitas_memory</value>
      <webElementGuid>cfaa1f84-50ed-434d-9f60-5be27f2ec9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-9 col-sm-9 col-xs-9</value>
      <webElementGuid>c2a1fdc6-c75b-4b3c-ae82-811d322fff63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kapasitas</value>
      <webElementGuid>035f0a30-ba32-4875-b26b-9399277f0341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kapasitas_memory</value>
      <webElementGuid>18cf0927-2e0a-4666-9f23-9191f9f7b8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kapasitas_memory&quot;)</value>
      <webElementGuid>4091121b-5803-4626-a807-fc7228ff222b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kapasitas_memory']</value>
      <webElementGuid>9400afbd-fdc4-4d6f-9707-86b0035ad6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[4]/div[4]/div[4]/input</value>
      <webElementGuid>c8117245-766c-4c83-ad7a-903732f1744d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/input</value>
      <webElementGuid>9ccef056-1b01-4fe5-91c0-008e0ae7592e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'kapasitas_memory' and @placeholder = 'Kapasitas' and @id = 'kapasitas_memory']</value>
      <webElementGuid>854c9cab-6c29-4b25-b489-4d832eb739df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
