<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_jumlah_hdd</name>
   <tag></tag>
   <elementGuidId>7ddc1d0c-b8bc-4315-b2b4-7537b576e35d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jml_hdd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jml_hdd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d13fdf1-2b6d-4afb-ad1c-f358eb3cd2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ca7c7a1e-442a-4850-9574-46a3dbe34298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah_hdd</value>
      <webElementGuid>94ca11a2-a6bb-497c-9129-f2eeec94f43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0729d6e1-fbf9-4516-ad85-e3a08c3b4b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Jumlah Hardisk</value>
      <webElementGuid>3ad0bfc7-6c47-4f8b-89bf-86fc6e67b309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jml_hdd</value>
      <webElementGuid>58d88b8a-5708-4d91-b1ce-a35d9b5e93cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jml_hdd&quot;)</value>
      <webElementGuid>47b3bff1-8f74-4780-a7ac-0e4137736911</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jml_hdd']</value>
      <webElementGuid>c1d9e646-065f-4a3d-a0db-0f59cfb7dc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[4]/div[3]/div[3]/input</value>
      <webElementGuid>6123d592-d5e3-4483-bcb2-0aa706b0902c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[3]/input</value>
      <webElementGuid>b7ee33df-3c60-4267-a139-34156fa730e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'jumlah_hdd' and @placeholder = 'Jumlah Hardisk' and @id = 'jml_hdd']</value>
      <webElementGuid>700f444f-d761-47ac-a5ec-752b5efe24b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
