<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjteknis_email</name>
   <tag></tag>
   <elementGuidId>177a8dfd-ca46-429e-a00c-4b79568bc18b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empjt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#empjt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4510855-3c53-491d-b57e-1534f6d5efc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empjt</value>
      <webElementGuid>8c9b0665-5176-435a-a280-4d91af67d706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjteknis_email</value>
      <webElementGuid>97864935-b22b-49cf-89c9-d7912416e6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a7ba3532-f75d-48b3-b414-979b52cd3413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control2</value>
      <webElementGuid>dcdbaa5d-727a-4920-b425-d17bbb29d99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empjt&quot;)</value>
      <webElementGuid>f8de72cf-93d3-4871-8512-6bfa89c2f37b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empjt']</value>
      <webElementGuid>1435a0ac-caf8-4bbb-8fbc-f7f135776af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form4']/div/div[4]/div[2]/input</value>
      <webElementGuid>b2277ae1-c82d-401f-808b-bf601fe9d616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/div[4]/div[2]/input</value>
      <webElementGuid>85547f0a-69e1-4754-bfeb-f922b7349339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'empjt' and @name = 'pjteknis_email' and @type = 'email']</value>
      <webElementGuid>46f3ba57-575e-44ea-8349-02c48e65f241</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
