<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nama_server_virtual</name>
   <tag></tag>
   <elementGuidId>fcb29ee8-a2e5-4939-b71e-a48ed541295b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='nama_server_virtual[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;nama_server_virtual[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5eb641f0-6bcc-4e3f-93d9-75d9728edf90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_server_virtual[]</value>
      <webElementGuid>f56cf173-cac9-48e3-8ff7-8fdbd1ddb569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e51ceba5-7db2-4f5f-9fef-7cf38c9dd7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>ab7353ae-4087-45ea-aac1-b1003d057e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Server Virtual</value>
      <webElementGuid>365edd76-038d-4b08-919b-4b43e1cd4cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insert-form&quot;)/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control required&quot;]</value>
      <webElementGuid>70d8589e-de94-4c46-9387-cc37cc6cae45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='nama_server_virtual[]']</value>
      <webElementGuid>b3541d0a-526b-44ca-a091-655b087629ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insert-form']/div[2]/div/input</value>
      <webElementGuid>8d6f1828-3ae4-43d8-b6a3-7d43cb950542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>07d56366-bb2b-4446-ba1f-0f7ed29dba9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_server_virtual[]' and @type = 'text' and @placeholder = 'Masukkan Nama Server Virtual']</value>
      <webElementGuid>5868dc7a-6ed0-409a-a31c-d6ba8a6901d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
