<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Pilih--                           _fd3fc5</name>
   <tag></tag>
   <elementGuidId>500fe6e7-0ea5-4210-97a5-65ce9d26d8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipe_storage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipe_storage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e420bbaf-09f1-4eb6-8608-4c993dfb1ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tipe_storage</value>
      <webElementGuid>aa493ca4-3e8a-4d85-9b81-46507d2a6c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipe_storage</value>
      <webElementGuid>be10401f-4548-40a6-aa45-0bfc9f31eb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d612ce10-eb42-4873-b056-7c657c1b415a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                --Pilih--
                                SAS
                                SSD
                                HDD
                            </value>
      <webElementGuid>4140c8f4-f61e-4381-8245-4a8f0c327e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipe_storage&quot;)</value>
      <webElementGuid>7385b8ae-849b-4ed7-9117-a0172180c005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipe_storage']</value>
      <webElementGuid>d1b608a6-9670-4503-ade1-38a9bf648a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[3]/div[5]/select</value>
      <webElementGuid>e4d109d6-53ac-4107-865f-e07eb262dbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/select</value>
      <webElementGuid>846ef7ea-bf8f-4a47-9f84-5e49f535fc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tipe_storage' and @id = 'tipe_storage' and (text() = '
                                --Pilih--
                                SAS
                                SSD
                                HDD
                            ' or . = '
                                --Pilih--
                                SAS
                                SSD
                                HDD
                            ')]</value>
      <webElementGuid>0b8ba88b-a856-4f5f-a166-cfa885993642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
