<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Pilih Nama AplikasiLayanan--Sistem_189b96</name>
   <tag></tag>
   <elementGuidId>f0783b63-19ce-4f81-a462-994d6c12ec71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_aplikasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_aplikasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dd434ad3-a1aa-470b-aa13-cfafdf0d23aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_aplikasi[]</value>
      <webElementGuid>119cf8e0-275d-4ffc-9d61-e9ab8001b4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>02e0192e-9bb7-4434-aee4-43c2340d0a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_aplikasi</value>
      <webElementGuid>d233086e-4361-47f9-a79d-7be666ec8362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Pilih Nama Aplikasi/Layanan--Sistem Informasi Manajemen Asset TIKLinggarjatitest rifkatesTestingTestingTestingTesting</value>
      <webElementGuid>dfec3463-f2fb-4efc-830e-afb1590d6db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_aplikasi&quot;)</value>
      <webElementGuid>fe656d93-55ca-4683-856e-0828b149495f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_aplikasi']</value>
      <webElementGuid>1d165674-13fd-4661-9160-254d77b8c2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insert-form']/div[2]/div[2]/select</value>
      <webElementGuid>0fd7b5ae-2893-46fd-8496-067e8478767d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/select</value>
      <webElementGuid>051f8f4f-9ec7-4582-93b3-717ebd1dd58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'id_aplikasi[]' and @id = 'id_aplikasi' and (text() = '--Pilih Nama Aplikasi/Layanan--Sistem Informasi Manajemen Asset TIKLinggarjatitest rifkatesTestingTestingTestingTesting' or . = '--Pilih Nama Aplikasi/Layanan--Sistem Informasi Manajemen Asset TIKLinggarjatitest rifkatesTestingTestingTestingTesting')]</value>
      <webElementGuid>8e475600-e2ea-444c-8926-f91e622a9352</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
