<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Pilih--                           _6dd8fa</name>
   <tag></tag>
   <elementGuidId>7eca991f-ab01-4e61-96c1-a83bf2d25bbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipePS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipePS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ef984c7e-02d3-4f04-81b4-f853cd59bc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tipe_power_supply</value>
      <webElementGuid>4559d6f3-b83a-4fba-99ae-eddcb4cddd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipePS</value>
      <webElementGuid>d573c72a-d9eb-45cf-8ac5-36af1f2fa98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b4c750b4-e37f-4330-a25e-992069c6a189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                --Pilih--
                                Redundant
                                Single
                            </value>
      <webElementGuid>9c446768-7b4b-48fb-9824-6ed895aa7a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipePS&quot;)</value>
      <webElementGuid>ed7d7466-35c0-4824-bd6f-074a73392119</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipePS']</value>
      <webElementGuid>30f18cf1-56c3-4479-87f2-3f809687e0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[5]/select</value>
      <webElementGuid>747cddbf-c440-4a38-8d98-467f3e89e55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>cc071182-c912-4bbd-a448-70c5815b90b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tipe_power_supply' and @id = 'tipePS' and (text() = '
                                --Pilih--
                                Redundant
                                Single
                            ' or . = '
                                --Pilih--
                                Redundant
                                Single
                            ')]</value>
      <webElementGuid>782e1040-5c4f-47d9-a22d-45d391a8b84e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
