<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_storage</name>
   <tag></tag>
   <elementGuidId>0e6a0909-f96a-4430-a294-6f942aaff72b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;storage&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='storage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>266d1ee7-fc35-4535-b741-f8ba827a381e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4d0fa95a-3f5b-4357-95cb-95b8beee0151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>storage</value>
      <webElementGuid>05c49efb-c84a-4280-a5b8-b0ff7cdd1471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-9 col-sm-9 col-xs-9</value>
      <webElementGuid>21389901-c262-47f8-93e7-75df36c37c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Kapasitas Memory. Contoh : 1024</value>
      <webElementGuid>99a693d8-811d-49dd-9b5c-dd4019b674d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4e62726d-9df5-4b9a-8f94-ec64d41a3b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;umum&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control col-md-9 col-sm-9 col-xs-9&quot;]</value>
      <webElementGuid>ba538249-33e1-479a-b2bd-0bc48fd749c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='storage']</value>
      <webElementGuid>4307ea33-2ca4-4d00-86a8-149f997d4b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[2]/div[3]/input</value>
      <webElementGuid>bd437874-615e-4550-8a37-0be8fb050a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>58c8e846-dd9d-4045-8a3b-ab582de85c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'storage' and @placeholder = 'Masukkan Kapasitas Memory. Contoh : 1024']</value>
      <webElementGuid>68defa08-c952-4e1b-be23-8b8eaba4fbcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
