<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_This field is required</name>
   <tag></tag>
   <elementGuidId>a3936d80-3192-4108-8803-aecc7061cdbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jml_transaksi-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='jml_transaksi-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>762a5e10-9495-415f-8ee5-70da9dd0052c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jml_transaksi-error</value>
      <webElementGuid>4bf35ce1-c544-4cc0-86c2-2511f15384ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>67ec96d5-2fbf-450e-b276-519dfd9ace86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>jml_transaksi</value>
      <webElementGuid>51505f4f-76c2-477f-88d1-8aec082851d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>195fe96d-0652-4704-9059-0effd58c9422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jml_transaksi-error&quot;)</value>
      <webElementGuid>1a7b5b35-4b6d-4a8e-8deb-3f0aa48019f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='jml_transaksi-error']</value>
      <webElementGuid>95c325c1-3624-417c-8e88-6f3a7a0737a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[3]/div[2]/label[2]</value>
      <webElementGuid>cbb004f1-027e-44e0-875e-9f365caa852a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>495de062-7201-4149-91b9-e155134dc54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'jml_transaksi-error' and (text() = 'This field is required.' or . = 'This field is required.')]</value>
      <webElementGuid>63039431-eb79-470b-a22e-b57ddb6759dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
