<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_email</name>
   <tag></tag>
   <elementGuidId>0a3e51ad-5336-4ff7-84c9-73b009348ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1bb2613-ed48-4f68-a5f3-263b7e103d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emv</value>
      <webElementGuid>989a004a-2e4a-4d98-8453-4ee9ed6d8ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_email</value>
      <webElementGuid>59bf7f72-6f36-44e6-a406-1cdcd458c207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ea38d699-147b-4715-b882-ce204b23f712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control3</value>
      <webElementGuid>2c8aad89-90f3-45bc-bbce-42b8a2624693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Pengembang Aplikasi</value>
      <webElementGuid>9ea64cce-c272-46f8-b70d-2252c058e6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emv&quot;)</value>
      <webElementGuid>9a06fa89-cd68-4721-9539-ea8fe7ad97d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emv']</value>
      <webElementGuid>53881914-f669-4e02-8741-22396854c492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[5]/input</value>
      <webElementGuid>4d1f2463-ae40-446f-868a-600fb37f11a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div[5]/input</value>
      <webElementGuid>0d9bf37d-81c8-4f88-96f4-03a0b8bd53b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'emv' and @name = 'vendor_email' and @type = 'email' and @placeholder = 'Masukkan Email Pengembang Aplikasi']</value>
      <webElementGuid>50e7789e-2a53-4968-aa1c-afa4a6bdef5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
