<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_username_db</name>
   <tag></tag>
   <elementGuidId>7ef77154-163c-444b-891b-1b80afc0854c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unameDB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unameDB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac19138d-4c17-48e4-8d2e-0729fdc4b599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b18d74c-34ab-45c9-a811-1bdaabc65db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_username_db</value>
      <webElementGuid>a4a2bb7e-6061-4b96-bb89-1622bfabb976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9e528be0-898d-40e9-9c85-019fe3bfebe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Username Database</value>
      <webElementGuid>54da9801-5f97-41c4-a739-4978300cde4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unameDB</value>
      <webElementGuid>dc7da39b-117b-43b0-a3d9-8316fd6472f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unameDB&quot;)</value>
      <webElementGuid>49c4af5b-d9bc-4aa0-9aca-46147c15bdbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unameDB']</value>
      <webElementGuid>be3b6ff2-db55-4687-9b60-581eb2badfe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[7]/input</value>
      <webElementGuid>7661893a-ae8b-4254-a20e-8f58384bc10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>e87f44c9-e7eb-41fb-a1b1-db0d135919c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'adm_username_db' and @placeholder = 'Masukkan Administrator Username Database' and @id = 'unameDB']</value>
      <webElementGuid>a652bc13-32fb-4a05-a228-9b6893e96327</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
