<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjteknis_email</name>
   <tag></tag>
   <elementGuidId>3ab74bf7-ffc9-42cb-a510-22bca2299aba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empjt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empjt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a3b4037-0db6-4b74-859b-bbd402f57ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjteknis_email</value>
      <webElementGuid>c8497036-576e-4e40-bf30-73aa53897c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ced3c53f-6e9e-4398-806e-8f299b7ea997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control2</value>
      <webElementGuid>6b0f760d-96c8-4485-ac02-012437c7e275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Resmi Penanggung Jawab Teknis Aplikasi</value>
      <webElementGuid>9d20c801-9639-481e-93ec-0a6615738cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empjt</value>
      <webElementGuid>ec6f049e-c7f5-44c1-ae0a-1819ad170cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empjt&quot;)</value>
      <webElementGuid>e51653ba-39e6-4f61-ac53-49282ca03038</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empjt']</value>
      <webElementGuid>568f12fd-c7cf-47e6-8098-daae2af30662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div/div[5]/input</value>
      <webElementGuid>99c910a0-8246-4cee-aecb-9aea00df7ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div[5]/input</value>
      <webElementGuid>f8852ac9-977f-49e2-b6f0-5c985ce3b220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pjteknis_email' and @type = 'email' and @placeholder = 'Masukkan Email Resmi Penanggung Jawab Teknis Aplikasi' and @id = 'empjt']</value>
      <webElementGuid>b053e9a8-f3df-4875-acd9-1e778db98f98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
