<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_email</name>
   <tag></tag>
   <elementGuidId>e7aa0df4-d5b4-4867-89ab-fdb1bdc98b92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ac04a1d-0c82-4c1d-938d-58848a62fde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>cb36e43e-6a76-434b-aef0-77ba98476953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control1</value>
      <webElementGuid>bf454e14-7c1f-4867-9b96-a9584c1d4c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_email</value>
      <webElementGuid>e379c2ca-c63c-478c-ac72-7ede04406ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Resmi Penanggung Jawab Kegiatan</value>
      <webElementGuid>06ff4d6f-f360-475f-9bf2-2d00d38b0224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empjk</value>
      <webElementGuid>939f563c-b7ab-42b8-a56d-468f230ccd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empjk&quot;)</value>
      <webElementGuid>42afad57-5827-478a-b157-ba856b6ca9cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empjk']</value>
      <webElementGuid>f70544f1-a0c1-47ab-aa1f-d86d3ac1e1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[3]/div[3]/input</value>
      <webElementGuid>667b6f9e-0899-4d09-bc6d-a4aef5592e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>43dbc86d-3b8a-4b88-ac3c-10302099d7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'pjkegiatan_email' and @placeholder = 'Masukkan Email Resmi Penanggung Jawab Kegiatan' and @id = 'empjk']</value>
      <webElementGuid>2d6a0b15-e8af-4552-a914-7706b9845d16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
