<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_alamat</name>
   <tag></tag>
   <elementGuidId>2b3c2e8e-cdf7-46c4-8f0a-8c6e2fdbaf73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alamatv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alamatv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1d1ee6e-a18e-4d56-8e0d-4d432ad9761c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_alamat</value>
      <webElementGuid>5e19db11-d446-44c1-a8d8-4b7dea75642c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95e877cf-1261-4186-803c-0d0066306781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ae478234-930a-4f74-aa1f-59155bfdb204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Alamat Pengembang Aplikasi</value>
      <webElementGuid>799af971-827b-478a-acc0-6fd6c8dde26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alamatv</value>
      <webElementGuid>ac106a5f-c151-42fd-be48-4a26257f873f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alamatv&quot;)</value>
      <webElementGuid>55636b14-f1e7-42c4-bf30-bd77ffccabf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='alamatv']</value>
      <webElementGuid>7e73c5f9-2177-47d5-96a8-1c77d21fd4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[2]/input</value>
      <webElementGuid>37ffaef2-5dd1-4d09-a073-25b163563d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div[2]/input</value>
      <webElementGuid>84ae8768-a531-47c2-8d42-11d50fc22d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_alamat' and @type = 'text' and @placeholder = 'Masukkan Alamat Pengembang Aplikasi' and @id = 'alamatv']</value>
      <webElementGuid>7765c2bc-fce7-421b-93af-8edd6744825b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
