<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_telp</name>
   <tag></tag>
   <elementGuidId>26cbc6f7-80a5-49d1-8a86-9d07b3580c87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telpv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telpv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57299d6f-e655-4d8b-870f-c04febce2469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_telp</value>
      <webElementGuid>75043dbb-c934-4ae9-bab1-c0645fb1660f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0c56ab04-6d43-4088-a39d-7d62cb7aa062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>16d73e4b-593d-4899-9a8e-74b713a53612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan No Telp/Hp Pengembang Aplikasi</value>
      <webElementGuid>3740f6fd-18df-4c5a-b1e7-a3420aa707e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telpv</value>
      <webElementGuid>3039089b-acea-4606-ba61-ec6d54dbf40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telpv&quot;)</value>
      <webElementGuid>b3d0dfcf-8d29-4910-9c16-4078d4884aa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telpv']</value>
      <webElementGuid>dde9dae7-b969-460b-8402-d536899a2bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[3]/input</value>
      <webElementGuid>9ae252c5-ef74-47c0-942e-c1e6797adf3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div[3]/input</value>
      <webElementGuid>6a67e8dd-ae4f-4b16-b07f-d1494ee60500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_telp' and @type = 'number' and @placeholder = 'Masukkan No Telp/Hp Pengembang Aplikasi' and @id = 'telpv']</value>
      <webElementGuid>5e8d7a76-8cb0-42d7-ba40-c7821efa30f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
