<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_nip</name>
   <tag></tag>
   <elementGuidId>3450fc45-d2b2-4159-8d61-9d80d7cc0361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nippjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nippjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff3e6dfb-099b-4812-812a-94b176415f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>98b7cf0c-4d3a-4447-a1c1-e1396dde27c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f86aaedf-f67c-4497-95a7-82b9c909ca08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_nip</value>
      <webElementGuid>e0f769ee-e58c-40e4-8573-70272688588e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan NIP Penanggung Jawab Kegiatan</value>
      <webElementGuid>84b950f1-41bc-4267-954c-e9083a5f6272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nippjk</value>
      <webElementGuid>fb62fe65-2302-404c-9732-9eb27b9e4795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nippjk&quot;)</value>
      <webElementGuid>fdbb62da-7ac0-433e-8c43-9377004cf47f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nippjk']</value>
      <webElementGuid>ef5f3d1c-f1c6-4f4d-ba63-d6dd3248d681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[2]/div[3]/input</value>
      <webElementGuid>d772b2aa-1d2a-43a2-a1a5-da52454fdc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div[2]/div[3]/input</value>
      <webElementGuid>a03fbc5e-a984-4d3a-b5cc-f4c7459f4716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'pjkegiatan_nip' and @placeholder = 'Masukkan NIP Penanggung Jawab Kegiatan' and @id = 'nippjk']</value>
      <webElementGuid>5df459b6-df89-4d2c-bc84-0afe83568c9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
