<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_nama</name>
   <tag></tag>
   <elementGuidId>d7082d73-d422-41bb-bef7-672a9f74dba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nmv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nmv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>999877bc-54f5-4615-a938-a3be6f414d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_nama</value>
      <webElementGuid>ac112c5f-31fe-49ec-8e20-5701ff3b54e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7f8618d-7ed4-4453-a3d2-2170c8e4da05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ad045fe9-e67c-403c-a411-47deae405dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Penyedia</value>
      <webElementGuid>b2813a9c-b4fa-483b-b7bd-bcbc1843945c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nmv</value>
      <webElementGuid>ff195bb9-1c2d-456a-a51e-f3a64958d674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nmv&quot;)</value>
      <webElementGuid>68f993f8-973a-4249-b753-bff4b57327b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nmv']</value>
      <webElementGuid>cdad46a4-e1ef-488d-8cea-4d8b9c0b41dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div/input</value>
      <webElementGuid>47c60754-ee83-4452-bc1b-6fc7ff9f8f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div/input</value>
      <webElementGuid>82f898cc-da76-4aed-948c-703c2cfbdab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_nama' and @type = 'text' and @placeholder = 'Masukkan Nama Penyedia' and @id = 'nmv']</value>
      <webElementGuid>82c97808-114f-4c25-a430-78f038875563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
