<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nama_aplikasi</name>
   <tag></tag>
   <elementGuidId>649a1613-5d32-4179-a000-40c63b519fec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nmapk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nmapk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c823855c-f44a-4a70-a8d0-517626be1e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_aplikasi</value>
      <webElementGuid>124087ef-d392-4d8f-8e73-f45fb159ad91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c91665f6-5773-4c9d-8068-26b74e614b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>fa149581-b072-4bc0-a753-917c33cd4e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Aplikasi</value>
      <webElementGuid>c2962169-ff11-49d4-a9cc-85f29860e8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nmapk</value>
      <webElementGuid>bdb50c6d-4fa0-4ab1-a33a-19db6071b9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nmapk&quot;)</value>
      <webElementGuid>763b9338-474e-46d8-bb66-0f706225c554</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nmapk']</value>
      <webElementGuid>af483509-8d57-47fd-8353-dcb363100a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div/div/input</value>
      <webElementGuid>c5e91d39-356c-4456-8ddc-52433a0f506a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>047db992-8748-4b5f-8558-92d51579c1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_aplikasi' and @type = 'text' and @placeholder = 'Masukkan Nama Aplikasi' and @id = 'nmapk']</value>
      <webElementGuid>23ee2eab-e435-4d16-ab24-9683599e260e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
