<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_port</name>
   <tag></tag>
   <elementGuidId>bd165211-caf3-4cb4-876d-5fd28f943ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#port</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='port']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09fe9ebd-4ed0-43b3-82ed-95431913f614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6677a4cd-da70-4a09-9f8a-79233d843ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>port</value>
      <webElementGuid>6f2d0ff8-3f9e-4b47-b354-dec5d715f2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>port</value>
      <webElementGuid>6e383d46-7af4-4785-8761-4f8061d174a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>87049c08-4045-4446-bc82-bb5f2899763f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan port yang digunakan</value>
      <webElementGuid>4481b6d1-b9da-4f53-9370-a41d8c2ade87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;port&quot;)</value>
      <webElementGuid>165daf73-e075-4e60-aed8-ca0cf5f47cc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='port']</value>
      <webElementGuid>d94bdfdb-54e6-4828-a0b5-43450a106ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[3]/input</value>
      <webElementGuid>2cae6f37-5ae1-481f-ba32-d57e29dcd633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>01dd0f97-7c2c-4fc6-b1cb-18a0e62a13f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'port' and @id = 'port' and @placeholder = 'Masukkan port yang digunakan']</value>
      <webElementGuid>56bcb21f-f8df-45aa-90e2-89941348b321</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
