<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_user_aplikasi</name>
   <tag></tag>
   <elementGuidId>edd67891-61a8-423f-92d9-d5ba9b365438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unameApk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unameApk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c3488f7-850b-4472-a9ad-0ef7c8072d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>195dd89b-a617-4162-b946-51e8c21442e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_user_aplikasi</value>
      <webElementGuid>afcf1a19-c6b9-4bac-9603-aac353f7bb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4272bf5b-b86f-4dd0-b2eb-fa6a23f1d994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Username Aplikasi</value>
      <webElementGuid>bd886f98-103b-4c1d-8871-96419c332d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unameApk</value>
      <webElementGuid>f8a16645-086c-4220-a49f-703938d92ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unameApk&quot;)</value>
      <webElementGuid>939694fd-c4bc-494c-810d-c4620710e6d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unameApk']</value>
      <webElementGuid>8e8c1dd4-2524-4373-9b81-1f45158639e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[5]/input</value>
      <webElementGuid>b0b0ba02-1516-4dc1-b223-4dedf70c887e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>550b6cbc-5a58-4271-9e2a-5e4ea6faf2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'adm_user_aplikasi' and @placeholder = 'Masukkan Administrator Username Aplikasi' and @id = 'unameApk']</value>
      <webElementGuid>2606f3ed-c135-4dba-be1d-0e098c7aaf02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
