<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_password_aplikasi</name>
   <tag></tag>
   <elementGuidId>d1d3fc2c-aac6-405c-85ca-104bb3e9643c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pwApk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pwApk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53d2122d-5602-48d9-bd7d-8461e1afd06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c5729fba-9b14-484b-8066-f2422535d94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_password_aplikasi</value>
      <webElementGuid>26303401-5c85-4e86-b293-8584d872431f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ffa7b13a-c3f0-4340-b0e6-bbc414f1a6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Password Aplikasi</value>
      <webElementGuid>5da8d7b4-b725-40b9-8d7b-c2775fc7d0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pwApk</value>
      <webElementGuid>4493178a-cf33-4760-b4ab-557ce3218986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pwApk&quot;)</value>
      <webElementGuid>c9b3ddb0-ab82-4f79-a08b-2dc4216bcbd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pwApk']</value>
      <webElementGuid>dc17af52-74be-4d3c-bf6b-7b4d61c251b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[6]/input</value>
      <webElementGuid>02ba38b4-26ad-438a-a720-e533afe764c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/input</value>
      <webElementGuid>e7cc114c-8114-4466-aa22-33f53e1bfabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'adm_password_aplikasi' and @placeholder = 'Masukkan Administrator Password Aplikasi' and @id = 'pwApk']</value>
      <webElementGuid>d08c5dff-bfa9-4586-99c0-c61047f566f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
