<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_telp</name>
   <tag></tag>
   <elementGuidId>362f3ac5-0f44-417c-8aa1-78ef937c3958</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nopjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nopjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1d72894-4388-45ce-9f51-54dc0e3bfa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fbf0bbfa-c06e-44cd-b21e-61144eaebdd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>723e087d-9199-4e50-8e9f-9585f97eddee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_telp</value>
      <webElementGuid>22368153-7a08-4e1a-851a-ea14f44b5fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nopjk</value>
      <webElementGuid>726f3ac1-7df8-45bf-89b6-f5d13083d94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan No Telp/Hp Penanggung Jawab Kegiatan</value>
      <webElementGuid>dda692ad-112b-4126-88c6-f0032d4542c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nopjk&quot;)</value>
      <webElementGuid>356e567b-885e-410a-b16f-b9af28dd60df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nopjk']</value>
      <webElementGuid>11b5fd1c-e398-4bb5-9ccb-4937f465ce47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[3]/div[2]/input</value>
      <webElementGuid>f070a1c7-e5c3-4115-8ce9-aaf2bac43d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>d8ac1f88-eed9-42fa-8daa-aefe2600ccb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'pjkegiatan_telp' and @id = 'nopjk' and @placeholder = 'Masukkan No Telp/Hp Penanggung Jawab Kegiatan']</value>
      <webElementGuid>b885b51f-3eb4-44b8-8d13-daaa7f0e59fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
