<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_password_db</name>
   <tag></tag>
   <elementGuidId>a96715a4-a626-4adb-8249-9d218725faef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pwDB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pwDB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c737723-4c23-4a53-933d-75ac530a8e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7eab04c9-74b3-4ef4-b607-49417cd4ca9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_password_db</value>
      <webElementGuid>740a4531-8e75-4015-97e8-369aa7f70f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>42efc04b-4522-447a-be71-dbee01d5d015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Password Database</value>
      <webElementGuid>fe41d9d4-840e-47c2-ad5f-23a4a5024945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pwDB</value>
      <webElementGuid>e176ecbe-e611-4152-a65c-ee298e4ac724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pwDB&quot;)</value>
      <webElementGuid>8e81a7a0-2ef1-42f6-84da-92219c9626d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pwDB']</value>
      <webElementGuid>8a25022a-a8ef-42bb-aaaa-683abd6b49dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[8]/input</value>
      <webElementGuid>d0a6569c-8d72-43fc-b1b7-1017667f1c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>301a2820-b2ef-4765-997e-a60256f49554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'adm_password_db' and @placeholder = 'Masukkan Administrator Password Database' and @id = 'pwDB']</value>
      <webElementGuid>69f6f1e7-3ace-4d63-ac77-c1cb1a6a58f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
