<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjteknis_jabatan</name>
   <tag></tag>
   <elementGuidId>e8cb7a56-cbaa-4d58-b44c-5fad92b29412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jpjt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jpjt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03dcde81-a3a6-42eb-8b96-11dcb9e8dd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1268d337-905b-4674-9464-012be6986333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>87012bfc-5c4b-4ba8-b837-7893ebc63c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjteknis_jabatan</value>
      <webElementGuid>c2d2c42b-04db-4982-b808-bb616f73ba57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jpjt</value>
      <webElementGuid>764e7caa-d753-48ad-a2c4-8c91e2ffa7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Jabatan Penanggung Jawab Teknis Aplikasi</value>
      <webElementGuid>42df8fa1-e0eb-452b-bbd8-a0666fb5e68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jpjt&quot;)</value>
      <webElementGuid>8cff6e14-1caa-45eb-b56b-1e867098e16e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jpjt']</value>
      <webElementGuid>7909b2f1-7e7f-48e2-a0fe-e921e8770406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div/div[3]/input</value>
      <webElementGuid>e6a60e3d-4979-45cf-924c-5626667b1e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div[3]/input</value>
      <webElementGuid>cf017226-f9e7-4a12-a996-fe3b3adc882d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjteknis_jabatan' and @id = 'jpjt' and @placeholder = 'Masukkan Jabatan Penanggung Jawab Teknis Aplikasi']</value>
      <webElementGuid>45cd8ae7-5b33-4e6f-99b8-6170ddc85772</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
