<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_jabatan</name>
   <tag></tag>
   <elementGuidId>4fc5be90-4f6b-484d-b29b-366a25178f8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jpjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jpjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69910882-8ed0-4193-a94f-6e32960ce1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b6bc5c5-432c-4b20-a752-a4245c8a904f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6f2bc863-aa5d-480d-af2f-51a2c28c12c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_jabatan</value>
      <webElementGuid>f864bafc-e9ed-4109-999d-fc6c80956421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Jabatan Penanggung Jawab Kegiatan</value>
      <webElementGuid>31ef5947-163e-46a2-87b8-66baf38d1caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jpjk</value>
      <webElementGuid>859ae335-fa85-4d6f-b97f-ecab24b95837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jpjk&quot;)</value>
      <webElementGuid>57416a06-ff88-41ef-952e-be7dcdcfaa49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jpjk']</value>
      <webElementGuid>e7d974be-c867-4c35-9df4-ab3d8694a68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[3]/div/input</value>
      <webElementGuid>c4a16822-4826-4dc4-be3b-14ff70aac1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>2aa76331-e55d-4ce9-9b47-dc32091be132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjkegiatan_jabatan' and @placeholder = 'Masukkan Jabatan Penanggung Jawab Kegiatan' and @id = 'jpjk']</value>
      <webElementGuid>abe144f6-f92c-4d28-966d-e4716c2b2528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
