<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Silahkan Pilih Status Aplikasi--  _fee1a7</name>
   <tag></tag>
   <elementGuidId>2fa925c4-86c9-45de-b42c-1ddda02d21e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#statusApk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='statusApk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>204fb3bf-6850-4e7f-b6a5-7bcea38d876d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_aplikasi</value>
      <webElementGuid>ae659aa0-b205-416a-9853-8e134897d26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>statusApk</value>
      <webElementGuid>edff5c3e-5244-4209-a99a-e9316514af61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>006182e9-684f-443a-99a5-1d126d7e7795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                               --Silahkan Pilih Status Aplikasi--
                               ON
                               OFF
                           </value>
      <webElementGuid>ba1fd71b-ade6-48fc-b63e-7220185e5e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;statusApk&quot;)</value>
      <webElementGuid>5b7c6388-cd3d-4c22-b03a-093a334b9b97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='statusApk']</value>
      <webElementGuid>322b7f3f-6936-471f-b5ad-628552afa3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div/div[5]/select</value>
      <webElementGuid>b460bef4-60ae-4045-a28a-2158508204a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>10ee6936-b1f9-445c-b475-5a9f04b91f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status_aplikasi' and @id = 'statusApk' and (text() = '
                               --Silahkan Pilih Status Aplikasi--
                               ON
                               OFF
                           ' or . = '
                               --Silahkan Pilih Status Aplikasi--
                               ON
                               OFF
                           ')]</value>
      <webElementGuid>b4e4dc5b-da8b-42c6-90c4-2b14ca0432e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
