<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih No Rekomendasi</name>
   <tag></tag>
   <elementGuidId>c0d4c520-9048-487f-a232-f485c3463d0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.chosen-single > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='no_rek_chosen']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>24ae9a8a-d82c-4b9d-a0f3-1131fc76be00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih No Rekomendasi</value>
      <webElementGuid>59d69d06-fd5c-43fc-92b2-83ef95ede5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_rek_chosen&quot;)/a[@class=&quot;chosen-single&quot;]/span[1]</value>
      <webElementGuid>7572eb95-2c41-4c3b-85ed-62fe4b2a6302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='no_rek_chosen']/a/span</value>
      <webElementGuid>c7cd24fb-f9ca-4970-8476-e7b0e959f249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/span</value>
      <webElementGuid>aa8783c4-5f95-4754-8eea-d7e1a7ace20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pilih No Rekomendasi' or . = 'Pilih No Rekomendasi')]</value>
      <webElementGuid>279d336d-566a-4ca5-a458-7db82d7c2cde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
