<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Unduh Modul</name>
   <tag></tag>
   <elementGuidId>fb742f7e-c7d6-4044-bc79-0b75d19b328a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='side-menu']/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#side-menu > li:nth-of-type(5) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2daf719-e5ce-4a28-abe2-cc025c4e9872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://linggarjati.kuningankab.go.id/Home/modul</value>
      <webElementGuid>fa6042a1-f80b-422c-8c65-933f918a41cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>blank</value>
      <webElementGuid>4ccf9ef3-f62f-4dfa-916d-f9ad86ed337a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Unduh Modul</value>
      <webElementGuid>330f3cb7-94e0-4013-b6a9-6ebff00ac76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/li[5]/a[1]</value>
      <webElementGuid>bfe4570a-f853-4d06-bc2b-b3d0ff7bfdf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='side-menu']/li[5]/a</value>
      <webElementGuid>2b83a3c3-2fdb-4be7-9369-76d0bcf17277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://linggarjati.kuningankab.go.id/Home/modul')]</value>
      <webElementGuid>6945f841-39e9-4413-a97e-681f6405675a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>8e83e546-4556-469a-9681-99bd75e7137e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://linggarjati.kuningankab.go.id/Home/modul' and (text() = ' Unduh Modul' or . = ' Unduh Modul')]</value>
      <webElementGuid>aacd2153-20ad-4d42-b720-14d1dcf8510a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
