<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>907e5647-8079-448d-b532-6e54b80f7c39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;simpan&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='simpan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93f8e89e-ac8b-48ac-b748-bd69f7bd8e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bc39ed04-2231-4108-807e-1495040407fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>simpan</value>
      <webElementGuid>44bdd1ac-43dc-4541-b0e8-45c81a56529b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>simpan</value>
      <webElementGuid>633cab28-fb21-442b-9e69-3bb242c672d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success pull-right</value>
      <webElementGuid>8edf8615-83c5-462c-8847-74ee88cd2975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Simpan</value>
      <webElementGuid>e60d8397-c979-489b-8280-6151157c7bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permohonan_aplikasi&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;form-group&quot;]/button[@class=&quot;btn btn-success pull-right&quot;]</value>
      <webElementGuid>5f53d3cd-40ef-4f33-9457-a8f558699a1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='simpan']</value>
      <webElementGuid>f085e6da-d871-4852-b742-06397e4f3bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permohonan_aplikasi']/div[4]/div/button</value>
      <webElementGuid>ba4b9dd6-b7fc-4705-b501-9470770b9b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>fb7ede8b-4cbe-4fc3-89f5-a2976bf4d870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'simpan' and (text() = '  Simpan' or . = '  Simpan')]</value>
      <webElementGuid>6ed25781-ad84-46e4-95b0-5c2529290ebd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
