<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tgl_akhir</name>
   <tag></tag>
   <elementGuidId>232a48c6-37e4-491a-85b6-cf801dafe112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tgl_akhir&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tgl_akhir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5955069d-7126-42f1-88db-49a1ae57add0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c18defba-01dd-4bc0-b31d-c0a2d45d12b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-control</value>
      <webElementGuid>393828dd-dae5-4fc0-afed-74cf1b9bcfe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_akhir</value>
      <webElementGuid>78269beb-24b3-48b5-8daf-89fe3a4a898a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tanggal Akhir</value>
      <webElementGuid>44b1e775-a54f-4c98-8a55-a81cac8198e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2f1624f8-3313-48a0-aca0-d71dc6fe4005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker&quot;)/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>7a8b813b-351c-4ec4-923a-d93a3f628570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tgl_akhir']</value>
      <webElementGuid>6de872b0-179b-4ef8-9c7a-03df48f19bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepicker']/input[2]</value>
      <webElementGuid>f13d36d3-d2f5-4e2c-bb58-3c13e91a3c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/input[2]</value>
      <webElementGuid>812d2fca-9b0d-4387-afe1-83ef9c128168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tgl_akhir' and @placeholder = 'Tanggal Akhir']</value>
      <webElementGuid>bb989b99-8c8d-42ab-9391-23dbb7b58429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
