<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please enter a valid number</name>
   <tag></tag>
   <elementGuidId>84b37afa-9edf-4105-b618-622f56b43109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pjkegiatan_nip-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='pjkegiatan_nip-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1ce30098-4f17-4dbc-8278-0ea329448823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pjkegiatan_nip-error</value>
      <webElementGuid>cd137c43-40fd-4e65-a6d9-3fb37fe82bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>b0153ef2-8357-4f2d-acc8-a54ddc343478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>pjkegiatan_nip</value>
      <webElementGuid>fc8e5514-c0bd-4caf-b59e-2edcbab31cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter a valid number.</value>
      <webElementGuid>602a47ab-2e9c-4388-9d3b-f961eef819f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pjkegiatan_nip-error&quot;)</value>
      <webElementGuid>fc5aaa24-6abe-4c56-8740-7fc458c5d5ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='pjkegiatan_nip-error']</value>
      <webElementGuid>9dcac4eb-b388-4c0d-969f-0e4d27cd1a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/div/div[2]/div[4]/label[2]</value>
      <webElementGuid>62004a3a-1007-4a8f-9dcd-87b8e76a313f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>48d7420e-b97c-48e6-b784-e3b7a6b61ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'pjkegiatan_nip-error' and (text() = 'Please enter a valid number.' or . = 'Please enter a valid number.')]</value>
      <webElementGuid>a0236b0f-5325-4486-95a3-dd78c2149891</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
