<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_This field is required</name>
   <tag></tag>
   <elementGuidId>0e197e4c-73da-4097-92b0-75e51efc3730</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pjkegiatan_jabatan-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='pjkegiatan_jabatan-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3edb8b0b-4932-46e3-95d9-8e03d2d489c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pjkegiatan_jabatan-error</value>
      <webElementGuid>747d6274-c440-45b9-bf8f-7ad018e30d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>d47f7618-1b3c-4414-bda2-34f6e59efe0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>pjkegiatan_jabatan</value>
      <webElementGuid>d2af4f06-cd19-4efc-8814-f86117c58368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>df3f6a85-db66-4a77-a3ab-f11d2eb0be17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pjkegiatan_jabatan-error&quot;)</value>
      <webElementGuid>8012bf82-a64f-4847-8015-b41d162e4e5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='pjkegiatan_jabatan-error']</value>
      <webElementGuid>9bfdba38-5fd6-4292-84f7-8d4cc102ad00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/div/div[3]/div/label[2]</value>
      <webElementGuid>6866d3e8-cdca-417a-a06e-3c521ba84d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/label[2]</value>
      <webElementGuid>17dc559a-3d98-46f4-a19e-ad3a26fa9b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'pjkegiatan_jabatan-error' and (text() = 'This field is required.' or . = 'This field is required.')]</value>
      <webElementGuid>8f7accd8-9814-450d-bcc2-5f127e343961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
