<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Baru                  Pengembangan  _55895e</name>
   <tag></tag>
   <elementGuidId>d62ac4ea-4999-4693-9ed5-d54c114981a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apl_pengembang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='apl_pengembang']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f7719a57-1764-4f48-9729-1a57249c940d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_pekerjaan</value>
      <webElementGuid>dac75337-deaf-4b69-a005-b5607601561e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apl_pengembang</value>
      <webElementGuid>972576a6-5d0f-4ebb-a662-a2bea7d55c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1157e167-1bcb-4cde-b177-8aced67acd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>660cd495-2045-462e-8402-7f1defc237d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Baru
                  Pengembangan
                  Berbagi Pakai
                </value>
      <webElementGuid>143de19f-b8ee-4031-ad44-2c828eeadb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apl_pengembang&quot;)</value>
      <webElementGuid>e79d3b86-ea38-41f4-8d9a-63d3b0c96b37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='apl_pengembang']</value>
      <webElementGuid>adc8c935-c2c9-4b05-8ae8-e37cd9af4f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permohonan_aplikasi']/div[2]/div[9]/select</value>
      <webElementGuid>a57d6766-c302-4d21-81d9-1e10989d0c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/select</value>
      <webElementGuid>d508f658-29fd-49b2-bd47-22e0fe618f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status_pekerjaan' and @id = 'apl_pengembang' and (text() = '
                  Baru
                  Pengembangan
                  Berbagi Pakai
                ' or . = '
                  Baru
                  Pengembangan
                  Berbagi Pakai
                ')]</value>
      <webElementGuid>6e1905cb-fcaf-48ba-a057-2115157f33ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
