<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_modul</name>
   <tag></tag>
   <elementGuidId>d9d9dba3-fa57-43d2-82ee-65a4cb33e3fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;modul&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id=''])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>67daf2f2-bf3d-4025-8a3e-ca7dfd1daa9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modul</value>
      <webElementGuid>29909d37-445c-4f60-8ce9-53227945fb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>2c4eba77-4f7a-4b12-a905-655093119497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>62e18f98-27d2-416e-8a00-83f4410d4b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9e93a779-8dc5-4ed3-9e0b-43e672c57bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isikan Modul Apa saja dalam kegiatan Anda</value>
      <webElementGuid>fcd8efb8-0a08-44d6-a9b1-1744d34cbc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permohonan_aplikasi&quot;)/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/textarea[@class=&quot;form-control&quot;]</value>
      <webElementGuid>1b886e2f-1deb-4bf4-90fe-0c997960fb56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id=''])[6]</value>
      <webElementGuid>0fcf889b-e43d-48f1-975a-1f99eaeae1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permohonan_aplikasi']/div[3]/div[2]/textarea</value>
      <webElementGuid>b7cbbad3-63b7-4c65-bd50-f627417fb73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>c0c02075-2459-4fab-8806-b0e5727e7f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'modul' and @placeholder = 'Isikan Modul Apa saja dalam kegiatan Anda']</value>
      <webElementGuid>ed985013-33db-48aa-bde0-707ae8e91130</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
