<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pendaftaran Aplikasi</name>
   <tag></tag>
   <elementGuidId>73603f57-94b8-4060-8074-b8890514f9da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.nav.nav-second-level.collapse.in > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='side-menu']/li[3]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e65ee8dc-5383-41da-ad70-5c121c28ea17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://linggarjati.kuningankab.go.id/Home/daftar_aplikasi</value>
      <webElementGuid>294d7bd5-5ac8-4e69-b936-cd3ab1b55a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pendaftaran Aplikasi</value>
      <webElementGuid>1b8ccb5d-609e-4937-bd97-9fa58a9be9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/li[@class=&quot;active&quot;]/ul[@class=&quot;nav nav-second-level collapse in&quot;]/li[2]/a[1]</value>
      <webElementGuid>b918d208-1870-40bb-8e29-c2097f76c480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='side-menu']/li[3]/ul/li[2]/a</value>
      <webElementGuid>9d6e51b4-6b62-4037-8927-4c9a90d3b0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pendaftaran Aplikasi')]</value>
      <webElementGuid>011f0d05-549c-4a92-af67-cdb24d46a158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://linggarjati.kuningankab.go.id/Home/daftar_aplikasi')]</value>
      <webElementGuid>66a27561-5837-4780-88ec-8ac376e7cdb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/a</value>
      <webElementGuid>7201e300-84a6-44ed-a258-b58f5ae896c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://linggarjati.kuningankab.go.id/Home/daftar_aplikasi' and (text() = 'Pendaftaran Aplikasi' or . = 'Pendaftaran Aplikasi')]</value>
      <webElementGuid>4e7ffb1f-59c1-46c1-a23b-96195b5ccc08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
