<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pilih No Rekomendasi</name>
   <tag></tag>
   <elementGuidId>93e4ed00-0f30-4602-b05b-d4179f76d07a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.chosen-single</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='no_rek_chosen']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>734ec71e-6990-4bb8-b937-84445b2c8ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-single</value>
      <webElementGuid>8abf96a3-55dd-4192-ad5a-10f934833246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4db5959d-e69e-4461-a102-405eabe89985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih No Rekomendasi</value>
      <webElementGuid>cb1b1da0-c0d2-4b1e-8220-e0a07ac3b4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_rek_chosen&quot;)/a[@class=&quot;chosen-single&quot;]</value>
      <webElementGuid>23a498ea-a800-4b32-a4ec-112dda7269d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='no_rek_chosen']/a</value>
      <webElementGuid>9cd7716e-d234-4044-b430-6f3bf818352f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>134f2872-9ea4-48ee-8af2-ead07c06d05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Pilih No Rekomendasi' or . = 'Pilih No Rekomendasi')]</value>
      <webElementGuid>e57ee4b1-5fae-47a9-88e9-282f4de91460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
