<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjteknis_jabatan</name>
   <tag></tag>
   <elementGuidId>7b184158-176f-4728-8a46-e02d6e831d5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jpjt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jpjt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b48f232-92c9-4c13-977d-a917bb23a184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>606d27e2-3449-4b1b-b98d-ea2e9bddd0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ebdb482e-35ee-48fd-a846-c843d281ef58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjteknis_jabatan</value>
      <webElementGuid>e7f17944-43bc-4b77-ad24-b5269f357241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jpjt</value>
      <webElementGuid>05e7c491-08e1-4e87-9638-37c5657da1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Jabatan Penanggung Jawab Teknis Aplikasi</value>
      <webElementGuid>93c69044-9d34-4338-8987-47f691ef462e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jpjt&quot;)</value>
      <webElementGuid>745af9e6-bde5-44a4-b189-8e224e4e8589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jpjt']</value>
      <webElementGuid>efccf416-5117-4c79-a179-9eabd92f5441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div/div[3]/input</value>
      <webElementGuid>c658e26c-b793-4961-8933-cf7db62779e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div[3]/input</value>
      <webElementGuid>e464c1ba-af23-480f-8e39-4d793ae14e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjteknis_jabatan' and @id = 'jpjt' and @placeholder = 'Masukkan Jabatan Penanggung Jawab Teknis Aplikasi']</value>
      <webElementGuid>be24819e-b597-42e1-ae03-568e756dbbb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
