<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_jabatan</name>
   <tag></tag>
   <elementGuidId>baf27ff8-cc60-44a9-8e60-6db7d21c2290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jpjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jpjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbb1b3bd-660e-4ee7-8986-c066e8ca95e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3f5c266-11d5-4a87-bc1a-3c22050fadc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1ecfe0bb-c538-4c7e-83ea-81edb25b0cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_jabatan</value>
      <webElementGuid>6b24f0d5-264b-432b-be87-c40321f9671a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Jabatan Penanggung Jawab Kegiatan</value>
      <webElementGuid>45bca1b5-4987-4d98-bc82-ca9b69d3cfe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jpjk</value>
      <webElementGuid>8072b333-0acb-4ceb-bc57-6fd35bcee153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jpjk&quot;)</value>
      <webElementGuid>df50cf5d-a6e5-43eb-ba2d-53440ff5e2f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jpjk']</value>
      <webElementGuid>9bf15a71-4f8f-4bf7-9ebf-143b50c37ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[3]/div/input</value>
      <webElementGuid>fb421fd6-23c6-4928-ba43-302be29f3b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>43ed1c6d-a5be-4161-888e-c3df2126c3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjkegiatan_jabatan' and @placeholder = 'Masukkan Jabatan Penanggung Jawab Kegiatan' and @id = 'jpjk']</value>
      <webElementGuid>a53ca315-f283-4bc0-a0bc-5d259b738afe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
