<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_password_aplikasi</name>
   <tag></tag>
   <elementGuidId>297a39f0-b357-478f-9bd8-103e3bf35f2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pwApk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pwApk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba2f7b7b-6295-4d6e-8e89-6c5ab9427eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c7b24f39-29e7-4f29-81d3-7b1ca8329267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_password_aplikasi</value>
      <webElementGuid>d6a95fcc-dd75-4774-8f2c-f24905f88fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9908964f-c804-413a-a8a2-6055013e78dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Password Aplikasi</value>
      <webElementGuid>7c856a74-2f54-4879-ae0b-18c550006913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pwApk</value>
      <webElementGuid>6f535b9f-7118-401d-9f8c-768c8fad2321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pwApk&quot;)</value>
      <webElementGuid>28b70931-8bef-4eae-8a4f-19f80f5255f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pwApk']</value>
      <webElementGuid>71f313d2-735b-4340-8fbe-a541cd88e39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[6]/input</value>
      <webElementGuid>07db219e-f771-4d1a-9bd3-fd9f619163d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/input</value>
      <webElementGuid>0076b336-bc17-41c3-b099-4434461cf5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'adm_password_aplikasi' and @placeholder = 'Masukkan Administrator Password Aplikasi' and @id = 'pwApk']</value>
      <webElementGuid>e33b631f-7323-48ba-9dc3-ea0520cff5cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
