<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjteknis_email</name>
   <tag></tag>
   <elementGuidId>af8a69ea-413f-4fb5-a24f-c5a4396d64ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empjt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empjt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c96135aa-1d2b-467e-ba6f-59d778877a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjteknis_email</value>
      <webElementGuid>89d2eeab-a4de-4658-a0fa-afbceea5e271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b12df92c-d492-4239-94a7-20089111a9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control2</value>
      <webElementGuid>61e379c4-80fa-4787-863c-8e2b0c8d1551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Resmi Penanggung Jawab Teknis Aplikasi</value>
      <webElementGuid>3eedf244-1f99-4e07-8595-8ceccb65f3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empjt</value>
      <webElementGuid>6248b92e-073e-4176-b1b4-2d2ec091105f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empjt&quot;)</value>
      <webElementGuid>97b24c5c-2dce-43a8-b486-c90f9cc7b140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empjt']</value>
      <webElementGuid>4d755af8-b2b7-4618-8af9-6d75eb9d2da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div/div[5]/input</value>
      <webElementGuid>1401d917-c7e1-45c6-9a2f-957d970eb4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div[5]/input</value>
      <webElementGuid>d39416fc-4f17-4897-8af9-e8c8b4df4103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pjteknis_email' and @type = 'email' and @placeholder = 'Masukkan Email Resmi Penanggung Jawab Teknis Aplikasi' and @id = 'empjt']</value>
      <webElementGuid>5e0cfb19-0499-44a6-8a24-3b40a1c3c566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
