<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_telp</name>
   <tag></tag>
   <elementGuidId>340ee2a0-9720-41b3-a166-7995e22ba193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nopjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nopjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>748affa2-a43b-49f4-b9a4-36e41f0d13c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>94062e8f-cb03-4cbd-a3d7-bc579e3c8e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b9a8776d-c651-4938-bc2a-032369a59375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_telp</value>
      <webElementGuid>b074b834-491a-4876-8cb6-2cf25167dc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nopjk</value>
      <webElementGuid>a7fb770e-5100-455c-9589-87bfc0099af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan No Telp/Hp Penanggung Jawab Kegiatan</value>
      <webElementGuid>28403676-9f5b-4716-b6c8-09ec9c6c3be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nopjk&quot;)</value>
      <webElementGuid>376d4a9a-9c26-449a-bcb0-9b64d48ba39c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nopjk']</value>
      <webElementGuid>009651b1-21d5-4210-be3a-f6d76a4db352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[3]/div[2]/input</value>
      <webElementGuid>b5713b6f-2ab7-4ad8-b261-932fc6f6bcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>d0161cf6-6e99-45b3-a1bc-ca90cc3a2c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'pjkegiatan_telp' and @id = 'nopjk' and @placeholder = 'Masukkan No Telp/Hp Penanggung Jawab Kegiatan']</value>
      <webElementGuid>7bde2d2b-909f-40cf-ae50-e004ab86adfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
