<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_user_aplikasi</name>
   <tag></tag>
   <elementGuidId>c1234cf7-2632-4d55-b303-9251b4909ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unameApk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unameApk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7eacc0af-3676-4a83-a10d-30e8ab52e295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ccd243c0-da1f-45b5-877a-71296527cd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_user_aplikasi</value>
      <webElementGuid>456e3458-9233-4872-93e9-2f08fd8101ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2ba7f842-0bab-4de7-87a4-7b469b27f35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Username Aplikasi</value>
      <webElementGuid>67b0f9a7-d0e8-4ae5-9f2d-c9a83a6eec2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unameApk</value>
      <webElementGuid>a1b5e8b6-9c37-49c1-93f7-c4a8c99a55ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unameApk&quot;)</value>
      <webElementGuid>b66d3262-1963-411c-a17a-084b2cb786dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unameApk']</value>
      <webElementGuid>43c7f336-f043-4a77-b03b-e455a0d068fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[5]/input</value>
      <webElementGuid>862accb5-6d3b-486f-99fb-d4bf55850202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>961aa3e2-6313-48ce-a36b-7df390de7415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'adm_user_aplikasi' and @placeholder = 'Masukkan Administrator Username Aplikasi' and @id = 'unameApk']</value>
      <webElementGuid>e613d7b5-9bdd-4449-a4ad-1c4a9f7b7e07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
