<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nama_aplikasi</name>
   <tag></tag>
   <elementGuidId>23f8945f-a136-4d41-89fd-6a672b2d3864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nmapk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nmapk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fd5ece2-4c72-4232-a6a3-f75c2530c400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_aplikasi</value>
      <webElementGuid>708d85ca-603c-40ae-9686-4780391d185b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd2c46ba-8d9f-492a-adf6-892435f9fe85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>1742d4eb-cbf7-4718-aab0-85d3c3ba34fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Aplikasi</value>
      <webElementGuid>15ea711b-dc20-44fa-8176-c0eccea07418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nmapk</value>
      <webElementGuid>e904a7c3-cd40-4ac0-afad-5a8d4e70664d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nmapk&quot;)</value>
      <webElementGuid>44cd2175-5662-4a84-8437-2848e04861a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nmapk']</value>
      <webElementGuid>e5149e76-9410-4c26-b495-979bca82b1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div/div/input</value>
      <webElementGuid>9fd49789-b0f3-4d42-9926-b74abd912183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d00db990-08bd-4e54-b2e9-323afb58a617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_aplikasi' and @type = 'text' and @placeholder = 'Masukkan Nama Aplikasi' and @id = 'nmapk']</value>
      <webElementGuid>51433cc0-edb7-4f57-ad20-f3db9339012b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
