<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_nama</name>
   <tag></tag>
   <elementGuidId>5617979d-8b43-42d1-b17a-22bf80bd2dd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nmv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nmv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db67d753-3e88-4ef9-80cb-a28a22faa04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_nama</value>
      <webElementGuid>71817040-e6dd-4ff0-978d-c3935dd670d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae9ac88c-46c2-455e-9964-a0265626f2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7a7d5fd5-2c9c-4a87-b9c7-918124f076ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Penyedia</value>
      <webElementGuid>97a302dd-244a-4642-8ab8-8ed00978f568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nmv</value>
      <webElementGuid>a68fed25-cf1d-49b5-9b27-adf6585d76b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nmv&quot;)</value>
      <webElementGuid>9fa8c3ef-d82d-4145-9c3d-57e3a39b335b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nmv']</value>
      <webElementGuid>4bcd1b5f-3824-4dde-bb77-26a53c87a17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div/input</value>
      <webElementGuid>e13f6338-3e5e-4c1f-a97c-f4c326b64d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div/input</value>
      <webElementGuid>484ee113-6ce8-4e7f-9654-42e027107043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_nama' and @type = 'text' and @placeholder = 'Masukkan Nama Penyedia' and @id = 'nmv']</value>
      <webElementGuid>7cc543c8-2b2b-483d-be1e-239ba48e5a7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
