<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_port</name>
   <tag></tag>
   <elementGuidId>05ed1fb6-e225-4675-8743-719282b1cd47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#port</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='port']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0103896e-e736-4f9e-be08-4aac7d49f7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0fd6624f-1458-47de-a519-e530254ccd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>port</value>
      <webElementGuid>579bf84c-fa6a-401a-ad5a-43bbfbc2055c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>port</value>
      <webElementGuid>3ac5d1cb-499b-4e4a-9454-72e2ae9ee621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>72084fd4-7ed7-4085-9283-778c7a137b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan port yang digunakan</value>
      <webElementGuid>fa921b3b-1d4a-42a2-990f-afbe712ee4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;port&quot;)</value>
      <webElementGuid>fc90a35a-fc47-48ef-b343-a2b3063c015d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='port']</value>
      <webElementGuid>cafe7f1c-d858-4e34-ad97-920495304353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[3]/input</value>
      <webElementGuid>6c8e6248-4463-4a4b-b5ae-0506036aeb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>2c79158f-ac53-4d3a-bb68-20032e8afb58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'port' and @id = 'port' and @placeholder = 'Masukkan port yang digunakan']</value>
      <webElementGuid>8074948e-b458-4ce8-97b7-3d252d4cb0cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
