<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjteknis_nip</name>
   <tag></tag>
   <elementGuidId>a2c452db-e46d-4896-9f15-447e12198666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nippjt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nippjt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef48d280-f4d1-4b38-a95f-161d5c2455ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nippjt</value>
      <webElementGuid>b7947257-4b12-423e-bf79-188c5c217df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjteknis_nip</value>
      <webElementGuid>09637434-935f-4bf1-9b55-a367ae645e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6d1fa06a-e851-4b87-882e-a50715d7fe9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bb31fa65-3893-4698-8d2c-6b9df54c2e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan NIP Penanggung Jawab Teknis Aplikasi</value>
      <webElementGuid>11029fa3-be5a-42cc-93dc-04ebd0a2dcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nippjt&quot;)</value>
      <webElementGuid>8be84721-7dc7-43b7-9f72-d631895d75ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nippjt']</value>
      <webElementGuid>8868f76f-8a84-4a48-bc41-3dd56af92728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div/div[2]/input</value>
      <webElementGuid>0dd30a0c-81cb-48cb-9a65-a73009946634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div[2]/input</value>
      <webElementGuid>e35cef9f-b4eb-483b-9d2e-2b5f1f020bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nippjt' and @name = 'pjteknis_nip' and @type = 'number' and @placeholder = 'Masukkan NIP Penanggung Jawab Teknis Aplikasi']</value>
      <webElementGuid>3e9cfc09-97b3-4038-8352-18a90594cacd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
