<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_username_db</name>
   <tag></tag>
   <elementGuidId>b864bb97-4c6c-4b0d-b3ff-aafd19cd08a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unameDB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unameDB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e41bfaf-3f21-491a-989b-8ab3adf45e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d0c922b-9969-4f19-8b6e-7e9cf266551c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_username_db</value>
      <webElementGuid>5d507aaf-a94e-4121-8bab-566df284ed44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>98218f89-b054-4ea8-8298-80ef06fa0076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Username Database</value>
      <webElementGuid>5ce5ec9a-993a-419d-bb32-d23d7d1f129a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unameDB</value>
      <webElementGuid>36d64316-5905-422b-9268-cb9ccae97131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unameDB&quot;)</value>
      <webElementGuid>3db403ca-9c24-49c3-be92-94ea3d8200c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unameDB']</value>
      <webElementGuid>ab514d1f-83fb-4603-84f4-14552199dda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[7]/input</value>
      <webElementGuid>9b7323c8-5036-40d6-a4b1-287ec390c94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>e62c41f3-801b-4206-905f-1c4677494084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'adm_username_db' and @placeholder = 'Masukkan Administrator Username Database' and @id = 'unameDB']</value>
      <webElementGuid>c5807d16-7efb-44ae-b738-fb829eed5ed8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
