<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_email</name>
   <tag></tag>
   <elementGuidId>dcba3235-4954-4e12-817e-ed7abe90a07a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4abd9e87-d838-4e24-bafb-8265eeda6461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>d7d22997-bc52-491c-9833-b49d7f7afdd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control1</value>
      <webElementGuid>4a4c2f31-2cff-4384-bfa8-0ede36d06b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_email</value>
      <webElementGuid>749b914a-3308-4ede-9c5f-e9f97287f72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Resmi Penanggung Jawab Kegiatan</value>
      <webElementGuid>85dcd0b4-8627-4368-8b3b-ca54681660a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empjk</value>
      <webElementGuid>4032eb68-6d14-4404-8149-df8c6a5e62f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empjk&quot;)</value>
      <webElementGuid>ee4a7fc1-0514-482b-81c5-38ea12d89f4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empjk']</value>
      <webElementGuid>f6a2f2c8-b0c8-4945-ab8e-e664521318af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[3]/div[3]/input</value>
      <webElementGuid>2941f2be-27e8-45a6-ba0c-78364b19839a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>059d055c-8f3e-4ca0-86da-38fb34f47711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'pjkegiatan_email' and @placeholder = 'Masukkan Email Resmi Penanggung Jawab Kegiatan' and @id = 'empjk']</value>
      <webElementGuid>8e2e62ad-283a-42d1-ab93-4b64abe6514b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
