<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_telp</name>
   <tag></tag>
   <elementGuidId>a1dd8de0-0361-4fe8-a861-6a615f88e8a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telpv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telpv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06639f9d-7854-49df-8ffb-1718347a2bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_telp</value>
      <webElementGuid>b443865f-915c-4e4f-b00d-f204ab3196fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ca4ce517-3fa7-477a-802f-af0abf1b14f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c9228625-9f9f-4103-810d-830bc7b85112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan No Telp/Hp Pengembang Aplikasi</value>
      <webElementGuid>4a4c4280-3af4-47f6-a0a3-c2c61bd0c7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telpv</value>
      <webElementGuid>24ac83ce-6022-4b60-b15a-9de1432f6aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telpv&quot;)</value>
      <webElementGuid>6649031e-c55c-411c-9e0e-00e5184550ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telpv']</value>
      <webElementGuid>eb0b1ac6-4865-4d28-abf3-ac814e488e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[3]/input</value>
      <webElementGuid>512ff348-273f-4695-b42e-8ca6278fc01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div[3]/input</value>
      <webElementGuid>2977c05d-b608-448c-b7af-11bd29bc3dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_telp' and @type = 'number' and @placeholder = 'Masukkan No Telp/Hp Pengembang Aplikasi' and @id = 'telpv']</value>
      <webElementGuid>d79ecb81-f236-4990-84f7-9502a3caaf0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
