<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_nama</name>
   <tag></tag>
   <elementGuidId>56076120-39c6-4655-a78a-81cbfe45a93b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nmpjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nmpjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>348404f2-d993-4f9a-83f7-c76196f55ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3eaad503-a386-42ca-8e6e-2a87eea8bf01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2cb1f9aa-9c8c-4434-86b8-2bd7ccc1bf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_nama</value>
      <webElementGuid>ae630fb5-471f-45c2-a1d5-b79022d927f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Lengkap Penanggung Jawab Kegiatan</value>
      <webElementGuid>a1d74911-4c1d-4269-adbc-5f0c57696795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nmpjk</value>
      <webElementGuid>1fb0532d-cd3a-4263-8a73-85b52f8e61c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nmpjk&quot;)</value>
      <webElementGuid>fcaebae7-dce8-4485-9d5b-97ca4b074a2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nmpjk']</value>
      <webElementGuid>6d8f42a2-a1fb-47da-95af-98309f1fddd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[2]/div[2]/input</value>
      <webElementGuid>b847d40b-9ec5-49ec-a1f3-7681eaedc8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>b9022b22-79c2-400a-afb5-97be2ad3f776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjkegiatan_nama' and @placeholder = 'Masukkan Nama Lengkap Penanggung Jawab Kegiatan' and @id = 'nmpjk']</value>
      <webElementGuid>357a8bd7-018a-4a71-9047-51a460591e93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
