<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_cp</name>
   <tag></tag>
   <elementGuidId>b527fa24-d2e4-4944-b2d8-e9de55623764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cpv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cpv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db89bc22-d175-455e-ab83-0041eaf3b18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_cp</value>
      <webElementGuid>7a71b625-a008-4643-b361-473692e1f9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14756ff6-bd6d-4785-99e1-833bd94ffd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cf9343f3-66a1-4a00-96cc-6533e210f6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan CP Pengembang Aplikasi</value>
      <webElementGuid>3d1392f7-f0f1-45b9-814a-b71d18af0387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cpv</value>
      <webElementGuid>502e5b85-e94b-40ff-88f1-cbd8289dd6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpv&quot;)</value>
      <webElementGuid>dd133ddc-f152-40a8-b12d-8320470e9a5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cpv']</value>
      <webElementGuid>9b8beebe-1913-4ed2-8a3e-6c4e2d773dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[4]/input</value>
      <webElementGuid>27d89a7b-ff8b-4caf-a476-43d9a0c1d1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/input</value>
      <webElementGuid>28d492cf-333c-4414-8945-6a7442934dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_cp' and @type = 'text' and @placeholder = 'Masukkan CP Pengembang Aplikasi' and @id = 'cpv']</value>
      <webElementGuid>1ff3322b-edcd-450b-9c9d-b33078518baa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
