<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_versi_bahasa</name>
   <tag></tag>
   <elementGuidId>a279c320-119d-45b4-a358-4683252cefa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;versi_bahasa&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='versi_bahasa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0e30745-1c96-43d9-89dd-2e12757f59b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da23574e-b7fa-4e4b-9102-0f1708c1f4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>versi_bahasa</value>
      <webElementGuid>4bb65e70-37a6-4ff8-b1fc-abe5e08e9cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-3 col-sm-3 col-xs-3 form-control</value>
      <webElementGuid>5d4a18d0-1399-4c22-acee-bd75ac9e70d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Versi</value>
      <webElementGuid>659ceac5-9c3e-469f-befe-7ed22762ea45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;col-md-3 col-sm-3 col-xs-3 form-control&quot;]</value>
      <webElementGuid>d3978bea-0a49-4411-a685-e63458024448</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='versi_bahasa']</value>
      <webElementGuid>ab75a743-beb4-4694-ba92-67882f63b53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[2]/input</value>
      <webElementGuid>5cfff163-5a17-4312-aa3a-680b4eea55a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>11c579a8-55df-41ac-a5c4-b9ed409ad3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'versi_bahasa' and @placeholder = 'Versi']</value>
      <webElementGuid>0c493ae5-c7f4-4cdf-a1b0-8a5489ccaead</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
