<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_email</name>
   <tag></tag>
   <elementGuidId>3acba168-9dce-478f-9919-6acb7451a008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21c0ca7a-9590-493a-a243-5b7e2fa44dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emv</value>
      <webElementGuid>f8fb68d9-0a91-4feb-9b42-ac61c3a15b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_email</value>
      <webElementGuid>705eb498-d3a9-4c37-8bc5-e6936fcb7c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8955fabc-3637-432d-a441-f87def4deb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control3</value>
      <webElementGuid>b2eb7f52-bb5f-45c9-9c3c-ba02d89307df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Pengembang Aplikasi</value>
      <webElementGuid>b5b78d0d-b143-4fee-b09c-c37db802ee76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emv&quot;)</value>
      <webElementGuid>33c26fef-fe03-4bb4-bf84-5e026552251f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emv']</value>
      <webElementGuid>12750808-1dd9-4965-b689-befa398c940d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[5]/input</value>
      <webElementGuid>9e707891-c2dc-4848-8259-4db48fe7f28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div[5]/input</value>
      <webElementGuid>b47eb1e4-88b7-4123-8a2a-c7a44b9ed1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'emv' and @name = 'vendor_email' and @type = 'email' and @placeholder = 'Masukkan Email Pengembang Aplikasi']</value>
      <webElementGuid>4f5c17c2-fcc8-4e9a-b270-cc42f75a0cd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
