<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_nip</name>
   <tag></tag>
   <elementGuidId>8190cc0b-886a-403c-8c6d-261ce0dd71ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nippjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nippjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f64635af-2096-4c89-b589-2dac9dafa326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f60f4173-a365-4b75-90b9-e08c60660cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cfbf59e4-6ea8-49d8-b065-66774a666ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_nip</value>
      <webElementGuid>228cfd26-d6f0-4565-9e5e-83fd5638debe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan NIP Penanggung Jawab Kegiatan</value>
      <webElementGuid>099a79b2-bd69-4637-9cb1-ee6c0e994077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nippjk</value>
      <webElementGuid>bd891119-d23f-4942-8401-c7df21cce6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nippjk&quot;)</value>
      <webElementGuid>1688b54f-2334-466f-be74-ed0e8da761af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nippjk']</value>
      <webElementGuid>b1dfee12-0bcf-4376-8f14-f5acc5c7e5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[2]/div[3]/input</value>
      <webElementGuid>9e7cb1d2-0fec-4050-b60c-ecdce51f7473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div[2]/div[3]/input</value>
      <webElementGuid>301ccb8c-c8c9-4e54-9af3-59510ed7b375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'pjkegiatan_nip' and @placeholder = 'Masukkan NIP Penanggung Jawab Kegiatan' and @id = 'nippjk']</value>
      <webElementGuid>9141e045-5cda-47dd-bda8-97c5a67c08ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
