<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_nama</name>
   <tag></tag>
   <elementGuidId>553d45c4-cf01-4176-988f-12843e434a0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_pjkegiatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_pjkegiatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ea45dd2-6de9-4b86-8f3c-8bc0b0361331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd26ab1e-0e42-46a9-88b8-4e1ebcc939d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>517bd53e-2cfb-4108-8d96-5a467e6a35b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_nama</value>
      <webElementGuid>7dce911f-5395-4af4-ae13-38faeacf2903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_pjkegiatan</value>
      <webElementGuid>83d675a2-ebf8-4d5e-bc1d-efa5ba09ad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f8577f51-e90e-4101-bf6b-3d7918ec16a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_pjkegiatan&quot;)</value>
      <webElementGuid>283c9438-fbff-4aba-a853-e4ab33c1457a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_pjkegiatan']</value>
      <webElementGuid>8701394e-0e0c-4951-8d5e-551485963ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[5]/div/div/input</value>
      <webElementGuid>e973bf36-6a1c-4cf4-b19c-b82b6ecb39c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>4ad927b9-4888-436b-9716-d9f60084aec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjkegiatan_nama' and @id = 'nama_pjkegiatan']</value>
      <webElementGuid>61721cbd-0fb8-419f-a73a-d09d43d6390b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
