<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Perangkat</name>
   <tag></tag>
   <elementGuidId>c05cd2da-41cc-4a3a-a99c-a407a42cca34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='side-menu']/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#side-menu > li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63663b4a-4db2-4513-901e-758c0a3faded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Perangkat</value>
      <webElementGuid>34324cb0-abdc-4724-b06b-2a22b0d6a940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/li[4]/a[1]</value>
      <webElementGuid>1044a1cb-1e82-43ed-b8b7-ab679ba1d7a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='side-menu']/li[4]/a</value>
      <webElementGuid>e83c99dd-b2ab-427e-addb-3944fc8b579d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[9]</value>
      <webElementGuid>379c6e8a-568b-48f7-9dfb-bb1fba8b9864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>6b9796d0-e59d-4025-8a47-b9fbd2e24c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' Perangkat' or . = ' Perangkat')]</value>
      <webElementGuid>f0b570c0-182d-4d39-b094-c952fc29a068</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
