<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Permohonan Baru</name>
   <tag></tag>
   <elementGuidId>c5aa8057-dd1d-4f8b-b599-82152d7faf32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='semua_permohonan']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#semua_permohonan > div > a.btn.btn-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b408cd1a-d356-45cd-85a6-5da466520cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-white</value>
      <webElementGuid>727b63be-9a5c-4092-8afa-e1c79dddc0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://linggarjati.kuningankab.go.id/Home/add_rek_colo/</value>
      <webElementGuid>22008cc8-c28d-4a3a-825f-555947ee1436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Permohonan Baru</value>
      <webElementGuid>78c9abb1-af91-4522-88d2-477aaab5e679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;semua_permohonan&quot;)/div[1]/a[@class=&quot;btn btn-white&quot;]</value>
      <webElementGuid>d5e2d752-eb9a-4822-943f-23961bfb82ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='semua_permohonan']/div/a</value>
      <webElementGuid>74978a45-ff84-4eec-82f7-3caa18acafb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Permohonan Baru')]</value>
      <webElementGuid>5cafce25-74dc-4bc2-8e3e-6193db752653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://linggarjati.kuningankab.go.id/Home/add_rek_colo/')]</value>
      <webElementGuid>a1260e5e-00b2-4d63-b00c-0432057da6dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>4c9d83ef-450a-442f-8b40-614b3ae6186c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://linggarjati.kuningankab.go.id/Home/add_rek_colo/' and (text() = ' Permohonan Baru' or . = ' Permohonan Baru')]</value>
      <webElementGuid>50b50383-114c-4e46-99af-22545798c6a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
