<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_This field is required</name>
   <tag></tag>
   <elementGuidId>36cbb1d9-653e-4893-a8c9-baa656672c97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='pjkegiatan_telp-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pjkegiatan_telp-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>61e2db02-b196-4e52-9e5b-60b49e585b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pjkegiatan_telp-error</value>
      <webElementGuid>59fd61ca-4157-4e68-8efc-be43bd5465e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>fa4d2254-eee9-4059-8747-d7fe676de64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>pjkegiatan_telp</value>
      <webElementGuid>ba8af5c5-b5b3-4d73-a3ea-66f0fcefd365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>c3bfafae-cf2c-4700-8619-a3ce1be3179f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pjkegiatan_telp-error&quot;)</value>
      <webElementGuid>9b78baad-8054-45bf-aefe-9534e1ecac97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='pjkegiatan_telp-error']</value>
      <webElementGuid>ac8433d2-a7e5-492c-a3f8-5117fba21ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[5]/div/div[4]/label[2]</value>
      <webElementGuid>f2077058-fce0-4d60-ad67-10f05a13025d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>371cbea3-8596-4974-b26b-afdc5beab86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'pjkegiatan_telp-error' and (text() = 'This field is required.' or . = 'This field is required.')]</value>
      <webElementGuid>d8d60cef-5afd-424a-8bc4-bda33e6a679b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
