<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Permohonan Layanan IP Public dan Subdomain</name>
   <tag></tag>
   <elementGuidId>305cf8a7-423c-4f11-baf1-43528cf5348e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='side-menu']/li[3]/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2aaa4ebe-ddc1-43c4-b87e-dc497e44786a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://linggarjati.kuningankab.go.id/Home/daftar_rek_ipsubdomain</value>
      <webElementGuid>fee30db3-4353-4111-aa52-731f88f2ea57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Permohonan Layanan IP Public dan Subdomain</value>
      <webElementGuid>d86e0e79-4f41-4839-bdde-92eb162bcaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/li[@class=&quot;active&quot;]/ul[@class=&quot;nav nav-second-level collapse in&quot;]/li[5]/a[1]</value>
      <webElementGuid>47b1a1a8-46b8-4b63-815e-2255fcca9286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='side-menu']/li[3]/ul/li[5]/a</value>
      <webElementGuid>dbc3fcd7-fe87-4cda-be2d-be8407f021b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Permohonan Layanan IP Public dan Subdomain')]</value>
      <webElementGuid>a0c6b97c-2404-4bd8-9bd5-d50ec722d352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://linggarjati.kuningankab.go.id/Home/daftar_rek_ipsubdomain')]</value>
      <webElementGuid>91289d39-57c8-4886-80a1-4492507d2055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[5]/a</value>
      <webElementGuid>ca0b95b9-a065-45c3-ae62-7a6143aa237e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://linggarjati.kuningankab.go.id/Home/daftar_rek_ipsubdomain' and (text() = ' Permohonan Layanan IP Public dan Subdomain' or . = ' Permohonan Layanan IP Public dan Subdomain')]</value>
      <webElementGuid>f76434e5-ff69-4466-aeb8-ea9e70d811db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
