<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tgl_mulai</name>
   <tag></tag>
   <elementGuidId>d031a887-9052-42c1-8d1b-697ae7d7d2db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tgl_mulai&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tgl_mulai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3def6ea5-0684-4440-85c0-5c1dff8e9f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73594eeb-6481-4bc9-b284-01f091b66b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-control</value>
      <webElementGuid>786e2ceb-5f0c-4cf2-b1c1-79b16414544e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_mulai</value>
      <webElementGuid>b4380563-b982-45cf-aa00-3c9e16be04f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tanggal Mulai</value>
      <webElementGuid>ffff935e-ab4c-4a4a-a2b7-8702dd23d695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3509584c-7dac-4afb-8796-f8167e486f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker&quot;)/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>cd676bfb-9bc4-47d2-8782-9286b516987a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tgl_mulai']</value>
      <webElementGuid>190607e2-dc91-42a3-8da7-8189c95eae90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepicker']/input</value>
      <webElementGuid>c98e1db9-425b-4991-929c-0494ac6f0702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/input</value>
      <webElementGuid>635a8ac1-ce0a-4290-8a13-a09442927727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tgl_mulai' and @placeholder = 'Tanggal Mulai']</value>
      <webElementGuid>c63edc12-df84-4120-92ec-8efc6e10c615</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
