<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please enter a valid number</name>
   <tag></tag>
   <elementGuidId>c7de4e3e-2c6c-4c98-805f-337e2a72a17e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pjkegiatan_nip-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='pjkegiatan_nip-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>dc3de73d-2340-46d4-ba35-5bbef732a042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pjkegiatan_nip-error</value>
      <webElementGuid>0c2313cb-e767-458e-8692-7e46349fd2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>47ca8225-936f-4088-8d68-d89532150694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>pjkegiatan_nip</value>
      <webElementGuid>6329b3d6-cbc5-40df-92a9-7bb4b4560b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter a valid number.</value>
      <webElementGuid>8a85d0ee-85ba-4729-a952-714e2482d4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pjkegiatan_nip-error&quot;)</value>
      <webElementGuid>126b88b6-8f21-4e03-8856-c2e56d366f29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='pjkegiatan_nip-error']</value>
      <webElementGuid>c40aaf49-7cbf-4a2b-8fa8-baf8290a8ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/div/div[2]/div[4]/label[2]</value>
      <webElementGuid>39f3abb4-c6c2-4592-8faa-831d4037814c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>540dd8e3-ec30-456c-b48e-04cd577601ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'pjkegiatan_nip-error' and (text() = 'Please enter a valid number.' or . = 'Please enter a valid number.')]</value>
      <webElementGuid>fab51c65-227a-429f-bf22-cddbbf2bfe1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
