<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Baru                  Pengembangan  _55895e</name>
   <tag></tag>
   <elementGuidId>b25d782f-fcb8-4cdc-bf44-2e821225b626</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apl_pengembang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='apl_pengembang']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c8d048dd-3734-4f1e-bd0e-ada381ae3f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_pekerjaan</value>
      <webElementGuid>8c32c0d8-4504-47e6-88a1-dcab1719df62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apl_pengembang</value>
      <webElementGuid>15aee017-7f6c-4bf4-b053-182545933b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>897ff4a4-35e5-46d9-af8e-6ca9dc18bbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f8179633-2bad-4bbf-9f04-4147ea70b9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Baru
                  Pengembangan
                  Berbagi Pakai
                </value>
      <webElementGuid>4e7dc519-e980-4f5b-a4c2-0d8c62af90ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apl_pengembang&quot;)</value>
      <webElementGuid>8aa7688c-fbce-4753-b95f-d711be79c956</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='apl_pengembang']</value>
      <webElementGuid>66118086-33b9-4c10-a7dc-725ed5a61cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permohonan_aplikasi']/div[2]/div[9]/select</value>
      <webElementGuid>3d0db5a0-d389-4515-bf4a-4e760dd5e6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/select</value>
      <webElementGuid>43bb17f0-0468-496f-9a13-dd2aaed2828f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status_pekerjaan' and @id = 'apl_pengembang' and (text() = '
                  Baru
                  Pengembangan
                  Berbagi Pakai
                ' or . = '
                  Baru
                  Pengembangan
                  Berbagi Pakai
                ')]</value>
      <webElementGuid>3caab8ba-82d4-49be-b3ef-0c247a3591db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
