<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Tidak Ada            Ada</name>
   <tag></tag>
   <elementGuidId>52d77776-b9c1-4985-a902-5bb8031a6933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ae73a323-9b41-46d3-90d8-563e5075aac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sop</value>
      <webElementGuid>9c6aa61c-5b88-4f55-a4a3-b1aef2ac4dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sop</value>
      <webElementGuid>54a38b28-03c9-4a47-9b6a-0be7e44a8b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4719850f-6c93-40d8-83f8-3aafc7e134c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2af8d7cd-c863-4b38-b9a0-4b245ebed414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Tidak Ada
            Ada
          </value>
      <webElementGuid>96b5fa9c-707c-4d8f-92f4-a94db7a780df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sop&quot;)</value>
      <webElementGuid>4d59cc1b-fe2b-4ee8-872b-76d6745907b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sop']</value>
      <webElementGuid>5e991732-8807-46b4-a3d8-72e77c58e70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permohonan_aplikasi']/div[3]/div[10]/select</value>
      <webElementGuid>8ddcaeca-86be-42e4-b2c7-f8601d659c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/select</value>
      <webElementGuid>a5ced787-e645-48b7-9be8-8afd85227877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sop' and @id = 'sop' and (text() = '
            Tidak Ada
            Ada
          ' or . = '
            Tidak Ada
            Ada
          ')]</value>
      <webElementGuid>d5c52d94-06f1-4367-8d0d-d84420691993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
