<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Permohonan Baru</name>
   <tag></tag>
   <elementGuidId>828a12ac-7dca-42da-9aa4-69ce9a378c50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#semua_permohonan > div > a.btn.btn-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='semua_permohonan']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ab64696-08e5-47eb-b1b2-c7177414470a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-white</value>
      <webElementGuid>a94dc0a9-04e6-493e-860d-487d8b03abfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://linggarjati.kuningankab.go.id/Home/add_rek_ipsubdomain/</value>
      <webElementGuid>c68d3fbb-b073-42cd-9fab-23a40265a8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Permohonan Baru</value>
      <webElementGuid>2e76e4f3-4d2b-462c-abe4-df3732fae175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;semua_permohonan&quot;)/div[1]/a[@class=&quot;btn btn-white&quot;]</value>
      <webElementGuid>2bc95f08-23b6-4f09-929a-1fc2dc78417f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='semua_permohonan']/div/a</value>
      <webElementGuid>673a8156-9443-4d8e-ad5c-ce5a02ca88d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Permohonan Baru')]</value>
      <webElementGuid>d87c8fc6-3bb9-4162-85c5-fa04c913754b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://linggarjati.kuningankab.go.id/Home/add_rek_ipsubdomain/')]</value>
      <webElementGuid>4d4e28c0-2019-4a43-b9d0-5a9dc90cde88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>8ff58bf7-c003-486d-ae04-41c53054ff61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://linggarjati.kuningankab.go.id/Home/add_rek_ipsubdomain/' and (text() = ' Permohonan Baru' or . = ' Permohonan Baru')]</value>
      <webElementGuid>8dc735b6-87d7-4bdc-9c6d-becf49024cfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
