<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_nip</name>
   <tag></tag>
   <elementGuidId>a57d2aa6-c8db-4239-b8de-4afe2ac1bdf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nip_pjkegiatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nip_pjkegiatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>016742ba-fb37-4003-a447-b77732fbca58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>06b79dda-0382-4b4e-9291-61b7a2b42c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2bc16c6d-654e-4a1b-a45e-17cc95366fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_nip</value>
      <webElementGuid>f96b5d69-5393-405e-b683-34d0bd51018f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nip_pjkegiatan</value>
      <webElementGuid>16cfff2e-d26d-4b91-be28-2e0e3bf08a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0b8c3e49-9e93-4598-a4cc-2efae6a86b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nip_pjkegiatan&quot;)</value>
      <webElementGuid>f777693e-d973-4e89-af7f-fd48c230da57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nip_pjkegiatan']</value>
      <webElementGuid>d4afbd64-e0fb-4b72-9fb5-b9f6bb4fbcb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[5]/div/div[2]/input</value>
      <webElementGuid>05ce6994-91e3-45e7-9bb9-71d10027c914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>e6f76e87-903f-4cd8-ad08-3185eb6862eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'pjkegiatan_nip' and @id = 'nip_pjkegiatan']</value>
      <webElementGuid>72037ef9-22a7-44b0-9add-c79457aac4c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
