<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_nama</name>
   <tag></tag>
   <elementGuidId>55586dea-b6a2-42a2-8039-5166af646044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_pjkegiatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_pjkegiatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aec3d07a-f39c-4939-a798-dfc73e384b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d83a4363-eb2f-453e-a065-0b3ce83e4cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2c951365-ec2c-4571-81e2-0a5db2b50bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_nama</value>
      <webElementGuid>502db410-30c5-4f41-8862-700f199c5f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_pjkegiatan</value>
      <webElementGuid>06acbfc3-5122-4121-8bed-249dcb073111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6adf6e48-5351-48e7-9915-b46c8a96f476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_pjkegiatan&quot;)</value>
      <webElementGuid>4e07dc76-d8dc-4347-9276-1762c7de7c90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_pjkegiatan']</value>
      <webElementGuid>dbc3cd72-3a98-4c81-8bfc-70a86da05db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[5]/div/div/input</value>
      <webElementGuid>8e4c139e-d7de-445d-b4c6-24f8fa1f5910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>3e766ac3-be8e-4f9f-9445-21b9e3a1c53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjkegiatan_nama' and @id = 'nama_pjkegiatan']</value>
      <webElementGuid>e5aa861e-da6b-402f-b2e4-db01815dc40c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
