<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_nama</name>
   <tag></tag>
   <elementGuidId>d0691347-a353-4651-b21f-c57b9da61733</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_pjkegiatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_pjkegiatan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5129bd5e-f01c-40d5-98ae-176fcd2eb5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>366c4088-4648-466d-a4ae-bb347b05f2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>71902342-4230-4b1e-ab45-4265aef81f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_nama</value>
      <webElementGuid>755d17b7-c84c-459c-85ad-8d3ed58a6016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_pjkegiatan</value>
      <webElementGuid>44d68bae-6910-4ce8-a0f5-a5649712b5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f2ce158c-0a6a-4ad6-8131-38d411b53cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_pjkegiatan&quot;)</value>
      <webElementGuid>452b9414-b0e8-4bfe-95e0-512ab4d3c2c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_pjkegiatan']</value>
      <webElementGuid>3cc74c05-7563-47b7-86d6-8bc79f0a0f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[5]/div/div/input</value>
      <webElementGuid>aface547-17bf-4541-97b8-8c34b8345310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>a4e83507-2400-4ce1-a1c3-8ebe56a9174d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjkegiatan_nama' and @id = 'nama_pjkegiatan']</value>
      <webElementGuid>07c13570-5a66-4e7b-acb2-dec3f6407f82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
