<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_memory</name>
   <tag></tag>
   <elementGuidId>97df055c-0bc7-49ca-9948-2e0b126b3bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;memory&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='memory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5250ca0b-c36c-42fc-8d1b-f84a570b5122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d1e40e40-2fb4-4d00-8ebe-d6db1c49b754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>memory</value>
      <webElementGuid>0514e7c1-331c-4878-8888-f39c664d32c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-9 col-sm-9 col-xs-9</value>
      <webElementGuid>fb6d4b0d-3ec2-48b4-b6c7-f3924b4211cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Kapasitas Memory. Contoh : 1024</value>
      <webElementGuid>dfed449e-e9a3-4ee3-9a71-2b68d7f0b949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>481e104b-3f78-4dca-baaf-771e3a304423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;umum&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control col-md-9 col-sm-9 col-xs-9&quot;]</value>
      <webElementGuid>4a205b6e-b75f-4bc1-8258-6689f44e5105</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='memory']</value>
      <webElementGuid>564ae7a8-655f-4838-bae8-675a4b281e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[3]/div/input</value>
      <webElementGuid>4b0e9e09-23b6-48c0-8c17-25fb12f1ff1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>232e7ef9-d055-4e8e-859c-c58124cf6451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'memory' and @placeholder = 'Masukkan Kapasitas Memory. Contoh : 1024']</value>
      <webElementGuid>45c39f98-7712-4741-89ab-90dc11c9d545</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
