<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please enter a valid number</name>
   <tag></tag>
   <elementGuidId>a38086ef-a37d-4eb0-a369-d83f70ef89b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#storage-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='storage-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4575b99b-68ae-4c3e-a678-fe59531224c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>storage-error</value>
      <webElementGuid>9dcd49dc-eb5d-4f42-b20e-25b8352b02f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>3df4ab39-f6f4-40c8-8ab3-2a32b1259c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>storage</value>
      <webElementGuid>4deb234b-1dfd-4ab9-9a6d-ff9890170031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter a valid number.</value>
      <webElementGuid>28f85951-2db7-42ef-8203-6392887600ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;storage-error&quot;)</value>
      <webElementGuid>22336ca7-e4c5-4f90-b6f6-1a605ad5a3e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='storage-error']</value>
      <webElementGuid>95cfc8a5-ff43-4ae6-8aa3-973c90ca9547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[2]/div[3]/label[2]</value>
      <webElementGuid>180c37cc-fbc4-4b81-9c6b-590d8ffced1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>7cc2332a-5d93-47f9-89c4-b7603b6d9b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'storage-error' and (text() = 'Please enter a valid number.' or . = 'Please enter a valid number.')]</value>
      <webElementGuid>906d5408-9620-418e-aa7c-0a0d71abce6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
