<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Perangkat</name>
   <tag></tag>
   <elementGuidId>b3e0ebe7-2714-4097-89cc-bf19b7da68a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='side-menu']/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#side-menu > li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ee6252de-0f55-40e8-b7b6-cb747d344fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Perangkat</value>
      <webElementGuid>abb9899d-accc-4049-997d-43d64e723fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/li[4]/a[1]</value>
      <webElementGuid>9dcc5dc6-9e19-476e-ad08-28ca503d6faf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='side-menu']/li[4]/a</value>
      <webElementGuid>cd45bee3-6bf9-48b3-bf69-25e318db9bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[9]</value>
      <webElementGuid>019cce78-f6f4-4723-b62c-ab18a9ac865f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>d4d9629b-7b2e-462e-bf2d-79a0794d01b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' Perangkat' or . = ' Perangkat')]</value>
      <webElementGuid>904aa27f-8405-45f4-a96b-3a9eb6ddde49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
