<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Permohonan Baru</name>
   <tag></tag>
   <elementGuidId>24ca2c27-a904-4e7b-938b-d6a0c8ed9121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='semua_permohonan']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#semua_permohonan > div > a.btn.btn-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e4cb083b-40fd-42eb-b644-6e462849cdbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-white</value>
      <webElementGuid>2df65db5-f516-4328-b090-434638d7e7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://linggarjati.kuningankab.go.id/Home/add_rek_perangkat/</value>
      <webElementGuid>ca1f1c6a-6d8e-4d9c-9c61-51a5d4503425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Permohonan Baru</value>
      <webElementGuid>4b82ce24-7b35-411b-b9fb-378b02390cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;semua_permohonan&quot;)/div[1]/a[@class=&quot;btn btn-white&quot;]</value>
      <webElementGuid>8ad1049f-587a-4f88-aa41-576a05d5853a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='semua_permohonan']/div/a</value>
      <webElementGuid>a3950a88-3921-4e2a-b636-6ef93b3783fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Permohonan Baru')]</value>
      <webElementGuid>3cadc7b0-b1cd-43fd-aa02-de56443c1ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://linggarjati.kuningankab.go.id/Home/add_rek_perangkat/')]</value>
      <webElementGuid>bb2dd007-09ad-4bfa-90af-e89788e0cd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>d38bb89d-c3a0-4819-8a16-58a79a2ca2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://linggarjati.kuningankab.go.id/Home/add_rek_perangkat/' and (text() = ' Permohonan Baru' or . = ' Permohonan Baru')]</value>
      <webElementGuid>81c3c3f3-479d-42d8-80fe-d0e20db254ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
