<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_nama</name>
   <tag></tag>
   <elementGuidId>c4d8f24c-a7c5-4a46-8dc1-ad77583c757f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pjkegiatan_nama&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pjkegiatan_nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c2beb1b-488a-4343-be47-d49e2800f4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9a5783c-d042-4eb9-aa93-bacbd8a63dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c134b58d-9891-4906-80cc-77a1a819aa0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_nama</value>
      <webElementGuid>c95ef3df-c9f2-457e-b867-7c2ddd23923f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isikan Nama Lengkap penanggung jawab kegiatan</value>
      <webElementGuid>b5560baa-5aba-44bf-ac64-00d82f9baaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5e316ea9-31b6-4561-8c4a-4d8fa63e01d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;umum&quot;]/div[@class=&quot;col-sm-6 b-r&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>3c1de7a4-a5f4-4b2c-a66c-90c4f48ed500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pjkegiatan_nama']</value>
      <webElementGuid>fa1c3702-a07c-4676-861f-ddfa848c3de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/div/div[2]/div[3]/input</value>
      <webElementGuid>847db11d-c7ab-43a6-8267-026226572d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>bd00f5b2-0e81-41ba-9bb0-b929bb494f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjkegiatan_nama' and @placeholder = 'Isikan Nama Lengkap penanggung jawab kegiatan']</value>
      <webElementGuid>f64c655e-a10b-4237-99f9-50b11798115f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
