<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tahun_anggaran</name>
   <tag></tag>
   <elementGuidId>f185b97b-d4b7-44e3-a14e-bb19dde57052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tahun_anggaran&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tahun_anggaran']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70c30466-c3e2-406f-8779-80173b74b38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>797090ef-575c-430f-9c73-d14241b1a1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d78a5cd5-25c7-4011-8584-09745177586b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tahun_anggaran</value>
      <webElementGuid>c11e397a-4e40-4404-a216-5ee306b07d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isikan Tahun Anggaran</value>
      <webElementGuid>878b6a28-fc98-4983-bc56-3a6cc37558d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fcd8a9cb-5f9e-4122-a9e4-f20e26e73056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permohonan_aplikasi&quot;)/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>21515c90-29f1-4404-a584-bea4c152b1f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tahun_anggaran']</value>
      <webElementGuid>a9a32cb7-88a0-436c-9406-d1902400209d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permohonan_aplikasi']/div[2]/div[3]/input</value>
      <webElementGuid>35f1aaa7-f097-4d75-92d5-dd656eb63552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/input</value>
      <webElementGuid>acaee6ea-b52a-493c-92bc-c43bd1d8b17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'tahun_anggaran' and @placeholder = 'Isikan Tahun Anggaran']</value>
      <webElementGuid>51b527c6-0099-41d7-bb80-06ce208eff69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
