<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_This field is required</name>
   <tag></tag>
   <elementGuidId>81285bc7-a8be-4443-8c3c-ec90e0539c70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pjkegiatan_jabatan-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='pjkegiatan_jabatan-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>70f5346e-323c-414e-9b05-2dbe573041f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pjkegiatan_jabatan-error</value>
      <webElementGuid>596b5b54-aa1e-42ee-b4fb-e0542db564f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>2db65d64-c450-4d32-8dba-09db03f03119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>pjkegiatan_jabatan</value>
      <webElementGuid>e08980f4-9a11-4338-bebd-884a55a83b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>f834ef64-bfc6-46bb-9597-c9895e4e2b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pjkegiatan_jabatan-error&quot;)</value>
      <webElementGuid>5809b0e3-233f-41f3-b308-b8c4583c677b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='pjkegiatan_jabatan-error']</value>
      <webElementGuid>dacb5b24-fe2b-444e-b4a5-598ac5d173e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/div/div[3]/div/label[2]</value>
      <webElementGuid>a74afec7-78c4-41ae-9e28-5fd2a8dd1cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>2c6afe6e-ca75-439b-af55-2a29746e5641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'pjkegiatan_jabatan-error' and (text() = 'This field is required.' or . = 'This field is required.')]</value>
      <webElementGuid>69638f4a-f22c-4bba-93aa-4defe7874767</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
