<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Tidak Ada            Ada</name>
   <tag></tag>
   <elementGuidId>b809df01-eecc-47c1-b08e-4dfa3bd502c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8ed1a9c4-dc1f-44c9-8af6-46dd9fadfac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sop</value>
      <webElementGuid>844ca0bf-d8dd-4693-ba12-aeea7b57f65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sop</value>
      <webElementGuid>61e4a13e-f13f-413f-88a8-f0d3237c7153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1cbcad78-2a50-4588-bd83-e51f59b65bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a359f0ab-e1ae-41ca-979d-eb5dc0997d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Tidak Ada
            Ada
          </value>
      <webElementGuid>d0b4c6ad-1148-4da9-9af6-95e4988923cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sop&quot;)</value>
      <webElementGuid>4d44d019-0b8c-477e-958c-ea0c82cd4e76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sop']</value>
      <webElementGuid>49c97960-aff7-410e-8c5a-a5d2d77fe6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permohonan_aplikasi']/div[3]/div[10]/select</value>
      <webElementGuid>85c33ed8-bda9-4d9b-bf9a-36b40bfea6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/select</value>
      <webElementGuid>2542de8d-f0ca-4c7b-b097-99bbf5f1005b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sop' and @id = 'sop' and (text() = '
            Tidak Ada
            Ada
          ' or . = '
            Tidak Ada
            Ada
          ')]</value>
      <webElementGuid>b99ce961-c1aa-409a-9738-ca6fbfb911d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
