<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Baru                  Pengembangan  _55895e</name>
   <tag></tag>
   <elementGuidId>51a5c4cd-4a70-424e-848a-24e1457e3ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apl_pengembang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='apl_pengembang']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4e61d767-f6f0-44ec-86a6-e93609431a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_pekerjaan</value>
      <webElementGuid>45afbe8a-98f8-4ba8-ad50-4e58d69ece2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apl_pengembang</value>
      <webElementGuid>24a411f4-a8db-4ff6-98db-c5bc3721e7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>958ccced-c441-40d0-b854-14b391d10bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>54123d39-45cd-4b06-a2a8-f8bb859fd1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Baru
                  Pengembangan
                  Berbagi Pakai
                </value>
      <webElementGuid>b904f54a-85b6-4436-9494-6c24b15104e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apl_pengembang&quot;)</value>
      <webElementGuid>a758c5df-bc8b-4471-aeaf-6722b5b39859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='apl_pengembang']</value>
      <webElementGuid>452528bc-b79f-49c5-a245-02670e94c092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permohonan_aplikasi']/div[2]/div[9]/select</value>
      <webElementGuid>c89fcb08-e238-4fac-ae8e-1fa42f5c559b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/select</value>
      <webElementGuid>72869a62-8d40-4a07-95e7-909f1679f018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status_pekerjaan' and @id = 'apl_pengembang' and (text() = '
                  Baru
                  Pengembangan
                  Berbagi Pakai
                ' or . = '
                  Baru
                  Pengembangan
                  Berbagi Pakai
                ')]</value>
      <webElementGuid>d9455818-d419-4fa2-91f6-1d53a5b96654</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
