<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya_1_2</name>
   <tag></tag>
   <elementGuidId>189cf5ce-7059-48db-aeed-c0d4524506b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='next3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9053f149-6b64-4faa-8232-d9a03c00beb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btnNext pull-right next</value>
      <webElementGuid>359cc942-77c4-43e2-a2e4-5a5cb61856ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next3</value>
      <webElementGuid>7ee105a5-31cd-4cd3-abb4-aabebd7dc235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>073fff8c-a4fa-48a2-8cf2-efa1cc6ebb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>362546c2-b7ac-4822-8269-20918f5e9775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next3&quot;)</value>
      <webElementGuid>94a28824-de5c-43ef-b3ad-deffd54b1de4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='next3']</value>
      <webElementGuid>4353c3f3-8728-4605-86d5-f473cf119606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[3]/button</value>
      <webElementGuid>785c374d-21bf-4727-8404-403197aa0a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[3]/button</value>
      <webElementGuid>83af0cf8-a8a0-4473-9c79-f82616619dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'next3' and @type = 'button' and (text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>e8b89f0b-9143-443f-aa67-b805ccd9a442</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
