<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-save</name>
   <tag></tag>
   <elementGuidId>98c76e5f-743f-4996-bead-00bf1c2f7c5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>476c07b9-3fb7-4672-9f75-2d69e843a2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-save</value>
      <webElementGuid>a6b15611-8f16-414b-923f-33910dfd6dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit&quot;)/i[@class=&quot;fa fa-save&quot;]</value>
      <webElementGuid>6dc15c30-28ff-4e71-ad71-74e8034a247d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='submit']/i</value>
      <webElementGuid>8c74b1ba-47a1-4e4e-91ea-eeb0de2b54c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>41a7f361-7ef7-40d7-b682-ea9c0b7ed256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
