<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_telp</name>
   <tag></tag>
   <elementGuidId>8bf3450e-0d7c-4afd-8162-8f146dfd244c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telpv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telpv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1253c5be-6b51-4819-b84c-cdfcee682e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_telp</value>
      <webElementGuid>d20af242-b109-46f2-b48c-cb7509720f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4ba42ccf-228e-4852-b5a8-7fbaa3e6b29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f5014a01-3d4c-4a8c-877c-5e629a28bb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan No Telp/Hp Pengembang Aplikasi</value>
      <webElementGuid>a362d5ee-8620-49da-b594-c4869e85ee55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telpv</value>
      <webElementGuid>95d3690e-b197-4b48-974d-5884fa266790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telpv&quot;)</value>
      <webElementGuid>1357aefc-f87e-4a1b-8d05-808930d34d45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telpv']</value>
      <webElementGuid>8cab955c-dfd5-49d5-866e-a8fcef51b758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[3]/input</value>
      <webElementGuid>2e3ba663-3212-4321-9d2b-5f614f7ed127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div[3]/input</value>
      <webElementGuid>9d121d58-0cc4-4237-a51c-aaf4e59622bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_telp' and @type = 'number' and @placeholder = 'Masukkan No Telp/Hp Pengembang Aplikasi' and @id = 'telpv']</value>
      <webElementGuid>3f70fb16-e2a5-42ac-8f35-e6d8c630cd9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
