<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_telp</name>
   <tag></tag>
   <elementGuidId>181094d0-045c-4578-9373-9e8a7fe7252e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nopjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nopjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c85d47a-7efa-428c-996f-70a098133255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c027cfdb-de8f-4857-b037-32b3a83d7b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>25c79a8b-afba-417b-b2a4-ad14f89aec31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_telp</value>
      <webElementGuid>aef79a66-3b1f-47ce-b9bb-a2e021afdc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nopjk</value>
      <webElementGuid>d2933892-0799-4a98-aba6-cc5f3d8482d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan No Telp/Hp Penanggung Jawab Kegiatan</value>
      <webElementGuid>d9113fff-ad07-4176-9ae2-dad8a56799e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nopjk&quot;)</value>
      <webElementGuid>249a1832-f917-40e3-8255-f05622fd8f68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nopjk']</value>
      <webElementGuid>d9ab9254-c7d1-49ed-a1b6-e9b1a665d17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[3]/div[2]/input</value>
      <webElementGuid>338afb26-7609-4016-b3e8-55f9388c0323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>4579ab75-e498-4088-a480-7c704649d9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'pjkegiatan_telp' and @id = 'nopjk' and @placeholder = 'Masukkan No Telp/Hp Penanggung Jawab Kegiatan']</value>
      <webElementGuid>c5f0d113-ab65-48d5-8b56-e36d440971e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
