<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_jenis_aplikasi1</name>
   <tag></tag>
   <elementGuidId>97291243-1d80-44d1-be6c-19998d8536a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;jenis_aplikasi1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='jenis_aplikasi1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9eb9ff6-753c-459c-a28c-39551fd33188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cb4c2d8a-a7e0-4c13-a681-41d3cf9d57c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenis_aplikasi1</value>
      <webElementGuid>dad33bf0-5778-459a-9b6b-0650a0345991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Web Base</value>
      <webElementGuid>b7a01c87-f04b-4f31-944a-b27283f4aafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/input[1]</value>
      <webElementGuid>54784987-b696-4bf8-a2fe-dc7df8647fd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='jenis_aplikasi1']</value>
      <webElementGuid>fa781a85-f510-4cb3-99d4-f18d69cd90e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div/div[6]/input</value>
      <webElementGuid>f2662230-9a62-4cb2-bd88-28940ee3876a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>530f2f4f-0bf2-4212-bd50-e4e63cfc4449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'jenis_aplikasi1']</value>
      <webElementGuid>09d9ce78-d919-452b-8dc9-04c1bb900844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
