<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjteknis_nip</name>
   <tag></tag>
   <elementGuidId>b53d860c-798e-4b15-8c88-50b2215759a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nippjt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nippjt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c81b2eec-e5e6-448e-88fc-3c1f133f8a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nippjt</value>
      <webElementGuid>bc34c87b-0658-4f5a-9322-193acad42cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjteknis_nip</value>
      <webElementGuid>7d20271c-a919-4861-8d74-99ed0ef95515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fddeb3ae-47de-4e8d-b886-109ba61f48af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>35d3b74c-90a7-446a-9600-90de3fd9fab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan NIP Penanggung Jawab Teknis Aplikasi</value>
      <webElementGuid>d21b7e0a-f396-4c4e-9991-d52891b02737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nippjt&quot;)</value>
      <webElementGuid>f2634917-a999-4295-bfc0-93801fee5f60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nippjt']</value>
      <webElementGuid>f6715444-12b1-4f5d-91ec-df37076fd0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div/div[2]/input</value>
      <webElementGuid>2e1d3c66-fac9-4f60-b727-1e6d4c584d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div[2]/input</value>
      <webElementGuid>56795680-90b8-4ad0-9892-bf1a874c2714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nippjt' and @name = 'pjteknis_nip' and @type = 'number' and @placeholder = 'Masukkan NIP Penanggung Jawab Teknis Aplikasi']</value>
      <webElementGuid>263dc9aa-cbcb-4f77-862d-cad19e8758cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
