<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_cp</name>
   <tag></tag>
   <elementGuidId>9dbfe04d-281e-4b71-a2c1-c9d50c2f6d2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cpv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cpv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a39ec764-2df3-402e-88a8-73642cdcddaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_cp</value>
      <webElementGuid>dd0c1be5-996e-46c0-a0fc-ca43ab93d2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c8cd1b5-a721-46fe-9dbb-6c1251873e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5561bedf-424a-4aa6-9264-7f055c20e402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan CP Pengembang Aplikasi</value>
      <webElementGuid>ee714a1e-c0ba-4e90-aeec-005b44cbdb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cpv</value>
      <webElementGuid>058aa6a6-948e-42e9-81cf-c69d27b825c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpv&quot;)</value>
      <webElementGuid>67b41e89-1b11-4754-ba9d-215ef4936bf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cpv']</value>
      <webElementGuid>ceb41fbb-54f9-4f8d-9bf3-c4b044a7d83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[4]/input</value>
      <webElementGuid>171bf86f-e500-4ea9-96bf-94052e267c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/input</value>
      <webElementGuid>5ce3e968-f98f-45d0-bec1-dd87791bc4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_cp' and @type = 'text' and @placeholder = 'Masukkan CP Pengembang Aplikasi' and @id = 'cpv']</value>
      <webElementGuid>66fdaa80-7cf7-423b-8b73-cd7400b8d36e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
