<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_versi_bahasa</name>
   <tag></tag>
   <elementGuidId>639fe300-b007-4850-8864-215320236880</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;versi_bahasa&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='versi_bahasa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ec97e09-c3d6-4319-b997-323d12d32ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e11090d0-8b65-44e4-bf97-44348fdf05cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>versi_bahasa</value>
      <webElementGuid>e2aaace4-731e-4c61-a35b-bc2e3b06022d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-3 col-sm-3 col-xs-3 form-control</value>
      <webElementGuid>6494450c-05ff-45c6-ad05-5897e7c8f5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Versi</value>
      <webElementGuid>6bd9f2f9-b429-47d0-991b-c12e18c8a7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;col-md-3 col-sm-3 col-xs-3 form-control&quot;]</value>
      <webElementGuid>73d19ccd-ba2d-4da1-99d0-c690369ff715</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='versi_bahasa']</value>
      <webElementGuid>6cdb2d3a-1d9e-4f76-b328-60fdd5e7234e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[2]/input</value>
      <webElementGuid>6cd0f739-7a0e-42b1-8d6c-bdd68a6f60f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>efd0c43e-3be7-4ca1-99e9-657658f90305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'versi_bahasa' and @placeholder = 'Versi']</value>
      <webElementGuid>663bd14c-2788-44da-9215-cccb66a2d354</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
