<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_jabatan</name>
   <tag></tag>
   <elementGuidId>d73cc0c0-7531-42e8-aa56-d5d78798cd4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jpjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jpjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96c5a07d-3c58-40d9-a2e0-39e04e08781e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>657170bc-c068-4ade-83fb-045f079a56fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>45ce3289-0dfa-480a-b484-910feee79043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_jabatan</value>
      <webElementGuid>b520e689-c801-4bdb-876f-31437230205c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Jabatan Penanggung Jawab Kegiatan</value>
      <webElementGuid>d746fbce-33f8-4c00-8c46-ec22f84162e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jpjk</value>
      <webElementGuid>8987db71-1c4f-4fbe-b182-dcd83acf0573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jpjk&quot;)</value>
      <webElementGuid>f04f6375-adc5-4459-b6ad-51c2be49ec4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jpjk']</value>
      <webElementGuid>8852f2d6-3878-48b3-ad32-fd8a529f5421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[3]/div/input</value>
      <webElementGuid>fea18afc-c41e-488e-8784-d1d3a0e06e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>a44f9494-db65-4c23-b103-85e61b3bf32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjkegiatan_jabatan' and @placeholder = 'Masukkan Jabatan Penanggung Jawab Kegiatan' and @id = 'jpjk']</value>
      <webElementGuid>f2aefe48-7d10-4524-9651-b470da97cb93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
