<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_user_aplikasi</name>
   <tag></tag>
   <elementGuidId>4951aea9-01d1-4a44-b427-da609aeb03d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unameApk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unameApk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>607aefda-3ef9-47fb-bb6b-ec98f31852fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d2c7bd1-d77b-4f10-815a-e0fad68b8873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_user_aplikasi</value>
      <webElementGuid>17a6b315-be3d-4f8d-a219-96835cf73941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a866cb24-840f-4c5d-a0e2-b70ef4e68be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Username Aplikasi</value>
      <webElementGuid>2050a5af-9386-4dcc-842b-e1af57112a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unameApk</value>
      <webElementGuid>54991394-1939-4b67-9ba4-45a5a94ed338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unameApk&quot;)</value>
      <webElementGuid>fe755098-c2b4-4320-9e2f-4c7baaf5a7a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unameApk']</value>
      <webElementGuid>8b7b2cf8-995e-490d-aa51-e66dc5cc7d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[5]/input</value>
      <webElementGuid>d050912f-68df-48ff-bf1e-959a483f6c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>2fa2b1b8-2793-40cc-acae-162c739bf253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'adm_user_aplikasi' and @placeholder = 'Masukkan Administrator Username Aplikasi' and @id = 'unameApk']</value>
      <webElementGuid>25ac2cb5-1aad-41d3-a5cd-3a50efef01d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
