<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_port</name>
   <tag></tag>
   <elementGuidId>217699c4-b62c-4a4d-a6c8-9ac8a539741f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#port</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='port']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1700728-2c69-447b-9a28-da289f585fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c3c5a202-6986-4102-a29c-acafa892055c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>port</value>
      <webElementGuid>aa37bef5-a2f5-4a96-8375-21da40e4d9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>port</value>
      <webElementGuid>24e485cc-bd49-4032-8fc7-312a004f6c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f8c8a201-6265-4bd0-bdf1-af6163c3a9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan port yang digunakan</value>
      <webElementGuid>0caf9527-e5ad-4276-b8c7-bc65de0c12f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;port&quot;)</value>
      <webElementGuid>2875bfcc-67a9-4ce5-a2c7-1e1620b7dd39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='port']</value>
      <webElementGuid>818debdc-20fd-4667-8fe0-126f018afc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[3]/input</value>
      <webElementGuid>767fc496-3369-4c67-9f30-5ca261f97e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>cfa58abb-82ac-4d4f-8ebb-75058f18e619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'port' and @id = 'port' and @placeholder = 'Masukkan port yang digunakan']</value>
      <webElementGuid>63e6e51a-4162-4d87-86f0-c579738a2909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
