<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_nama</name>
   <tag></tag>
   <elementGuidId>fb70775b-0176-491e-9244-6f83ea6cfb45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nmpjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nmpjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>006f041b-6af0-427e-9495-7c9e7a936d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9165ca88-cecd-4238-8231-b0884c55aedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>512f3349-6a5a-4cc3-822f-b9666bfcb188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_nama</value>
      <webElementGuid>27638b8a-3d9f-41bd-ac08-4f2656d01cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Lengkap Penanggung Jawab Kegiatan</value>
      <webElementGuid>391275df-63ad-472f-aa27-857b705abe71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nmpjk</value>
      <webElementGuid>57f5987b-fdb5-44b1-96a6-89a9b0eccd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nmpjk&quot;)</value>
      <webElementGuid>ff99ae3c-82c1-409e-8a09-12c640d2261f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nmpjk']</value>
      <webElementGuid>ebeba726-5140-43dd-b431-22b12c455e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[2]/div[2]/input</value>
      <webElementGuid>c5941ea5-ded1-40c9-9968-9e7d15f49a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>ac1f2d2e-4e01-43ee-8672-a05bfff4c4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjkegiatan_nama' and @placeholder = 'Masukkan Nama Lengkap Penanggung Jawab Kegiatan' and @id = 'nmpjk']</value>
      <webElementGuid>2def6eeb-2d62-41d6-8ecd-4b73bdaad0fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
