<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_nama</name>
   <tag></tag>
   <elementGuidId>31612042-5f89-4453-8998-fc399fecf070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nmv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nmv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8331689-5f8b-4e2c-9918-de891fe29619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_nama</value>
      <webElementGuid>ca3ee9bc-3194-43d7-b4aa-87ae7893cde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38f57287-0436-4e2c-be10-213c23431501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9e8ac5c2-1587-4d37-a0ce-352f3619a4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Penyedia</value>
      <webElementGuid>0abc6daf-12bf-486f-a0b7-2745605a5988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nmv</value>
      <webElementGuid>fcb9a40b-55db-4906-bde1-dfcaf82391b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nmv&quot;)</value>
      <webElementGuid>c962c70f-4eb2-411f-b4f9-7be6c4fd7b5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nmv']</value>
      <webElementGuid>9119b498-e59f-400d-9029-98a7fd4abb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div/input</value>
      <webElementGuid>21057915-b288-4c10-a802-ef0c65117a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div/input</value>
      <webElementGuid>e556c052-9b15-4278-8588-e9b8e34a9c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_nama' and @type = 'text' and @placeholder = 'Masukkan Nama Penyedia' and @id = 'nmv']</value>
      <webElementGuid>d2d7e31f-1059-4d02-9b4a-971a00101e05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
