<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_username_db</name>
   <tag></tag>
   <elementGuidId>f6cad6a9-f292-417b-95cb-9046b4811a2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unameDB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unameDB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>776c076a-d542-4fdb-b6aa-998dff89ae21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11500f29-46f7-47b5-b28f-39b56830bf4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_username_db</value>
      <webElementGuid>2e5b1d98-0766-4aa4-8140-fa82d8cd91e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dba77a2a-664b-44b4-b3af-b1e57c111982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Username Database</value>
      <webElementGuid>11626aa6-0279-497e-b69a-f1fbcd10682d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unameDB</value>
      <webElementGuid>ac7e99aa-b21c-4bbc-845d-cbdd4333d32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unameDB&quot;)</value>
      <webElementGuid>6c88d29b-4f3a-4492-9100-84cd07df4542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unameDB']</value>
      <webElementGuid>a1ae8933-7c14-4e53-b0cc-abd16f0b3a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[7]/input</value>
      <webElementGuid>2f08efb3-cf0b-4b69-881d-ca502ab3712c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>0a983102-ef77-45f9-8b3a-fbc2c9d32e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'adm_username_db' and @placeholder = 'Masukkan Administrator Username Database' and @id = 'unameDB']</value>
      <webElementGuid>91beb60d-e9b7-416a-99a0-6692510bfb1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
