<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_alamat</name>
   <tag></tag>
   <elementGuidId>85165a05-672b-4c19-8d7a-9e33613a0ef5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alamatv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alamatv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4aefa82-42f4-47e0-aa11-c0c2c3c93d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_alamat</value>
      <webElementGuid>7d4e857b-bd99-4375-99d7-faa228cb588f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6d23463-1058-4ae3-9524-26ead44f6e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>40aed9ce-9390-4987-bc6a-02daa20d5424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Alamat Pengembang Aplikasi</value>
      <webElementGuid>700a668f-0378-4796-87b8-864e8968a84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alamatv</value>
      <webElementGuid>8f569573-23c8-40d7-973a-ce0e999e783b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alamatv&quot;)</value>
      <webElementGuid>542aec76-768a-4b20-bab8-fb404cb8112b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='alamatv']</value>
      <webElementGuid>2b988d87-f08b-44cc-82af-faf897461eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[2]/input</value>
      <webElementGuid>f72a33a0-b183-4674-a555-a160358ba699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div[2]/input</value>
      <webElementGuid>0cfdd06a-0b04-4ba8-8de9-2130e7183a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_alamat' and @type = 'text' and @placeholder = 'Masukkan Alamat Pengembang Aplikasi' and @id = 'alamatv']</value>
      <webElementGuid>a0ba9043-9d9e-4a49-872e-31e6caffca62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
