<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nama_aplikasi</name>
   <tag></tag>
   <elementGuidId>a1e21821-6b60-469d-aa32-af22bbd7f463</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nmapk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nmapk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>865af2fd-9fc0-4374-b23e-3a7365294b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_aplikasi</value>
      <webElementGuid>fed4be32-cca9-4aa3-81a2-808f7b1da758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8586fcd3-9bd0-483f-9c2c-96664513d515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>ce348a5c-46e3-4af0-8d26-a5c9e6a2457d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Aplikasi</value>
      <webElementGuid>00f14a75-0eb7-43db-a81e-f37ea666db92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nmapk</value>
      <webElementGuid>4bcaaae0-0d9c-48e6-a2ba-d73ded18b6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nmapk&quot;)</value>
      <webElementGuid>ef188a68-a365-4d54-b129-f6ba1e30dc53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nmapk']</value>
      <webElementGuid>085fba0e-4492-4103-bf58-71441b2a24c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div/div/input</value>
      <webElementGuid>74ad9230-5b8f-4fed-93b8-5e6c657e02ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a872885b-c895-455d-9c22-0448e14500d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_aplikasi' and @type = 'text' and @placeholder = 'Masukkan Nama Aplikasi' and @id = 'nmapk']</value>
      <webElementGuid>029d633f-8a73-427c-b543-183963c82e87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
