<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjteknis_email</name>
   <tag></tag>
   <elementGuidId>9f129fd6-d7ae-497f-9319-05666cf14db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empjt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empjt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbb56cd4-ecbb-4505-b8f8-d6444adba143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjteknis_email</value>
      <webElementGuid>4a344376-4e30-49cc-8164-642033429b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f38b3137-af6a-484d-a0ed-d3e9a5bf2c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control2</value>
      <webElementGuid>5a3063a8-baad-4eb6-a22d-a0c08ef41877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Resmi Penanggung Jawab Teknis Aplikasi</value>
      <webElementGuid>85b53cb0-a516-4176-83b0-fab80a0309af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empjt</value>
      <webElementGuid>42904721-fa5a-45d0-ac3e-b14be971ba3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empjt&quot;)</value>
      <webElementGuid>f857919b-8dcf-43d3-a608-81c777dd427e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empjt']</value>
      <webElementGuid>c67d471e-fba9-498b-bbc2-f146698d24a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div/div[5]/input</value>
      <webElementGuid>9f1c3f6f-fbf5-4970-b4af-8b1715208267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div[5]/input</value>
      <webElementGuid>c4f9ff9f-8fc3-4102-b33f-e086be9bdb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pjteknis_email' and @type = 'email' and @placeholder = 'Masukkan Email Resmi Penanggung Jawab Teknis Aplikasi' and @id = 'empjt']</value>
      <webElementGuid>c2a3c60d-750c-4746-abdf-3726aa9f896f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
