<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_nip</name>
   <tag></tag>
   <elementGuidId>db71c5cb-8593-488c-b87b-951943755b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nippjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nippjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52afb6e6-9e11-4583-a392-a0aa9ff51d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>59daf3ba-60a2-4af7-bb09-3e378dfcf1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9bbc56f0-6d17-4d58-af41-74e6595104aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_nip</value>
      <webElementGuid>7b61c338-aa82-49a3-9405-d62e5a4003ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan NIP Penanggung Jawab Kegiatan</value>
      <webElementGuid>9836ff8e-5abc-42f9-adc3-01cd892e0686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nippjk</value>
      <webElementGuid>d5ce05fb-8617-41ca-8bf3-d10609f2a001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nippjk&quot;)</value>
      <webElementGuid>804ac21b-26f4-43fc-b70d-ce6f7e561dd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nippjk']</value>
      <webElementGuid>2360d57e-e526-4869-a7c0-ca05d2591b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[2]/div[3]/input</value>
      <webElementGuid>5138fa19-2d44-4687-b975-a79f139681d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div[2]/div[3]/input</value>
      <webElementGuid>d77ed9ab-afb7-4b4f-b125-1e7fdc57cb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'pjkegiatan_nip' and @placeholder = 'Masukkan NIP Penanggung Jawab Kegiatan' and @id = 'nippjk']</value>
      <webElementGuid>b50ee8a2-8188-4b54-b785-047b78e83b68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
