<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_alamat_url</name>
   <tag></tag>
   <elementGuidId>08cf306c-bbe5-4ab3-bf1b-6004dd5954c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#urlapk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='urlapk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28ee9209-4d5e-4481-8ae5-798d38ae5dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat_url</value>
      <webElementGuid>48ffd5b4-798d-4d64-ac36-d6c43c54ae73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11fb0795-aaa9-4350-b789-3c5403efd15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>549d9f04-bb59-4cae-a96a-1338bcc10b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Alamat URL</value>
      <webElementGuid>039e0ac0-74b2-4ac5-b2bf-628d02748aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>urlapk</value>
      <webElementGuid>df71c006-6691-4baf-bbce-4a4ba063f8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;urlapk&quot;)</value>
      <webElementGuid>d1f6609f-975f-48af-8aab-6ab5aac5c9f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='urlapk']</value>
      <webElementGuid>50542adf-8d1e-4a40-ae48-1fd582b343a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div/div[2]/input</value>
      <webElementGuid>649395f8-93c0-4e3e-9747-58e0e5957fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1a2444da-17db-4b48-abed-4e5bc3aae3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'alamat_url' and @type = 'text' and @placeholder = 'Masukkan Alamat URL' and @id = 'urlapk']</value>
      <webElementGuid>a2bc34bd-621d-4907-82cd-f3c21c5c12f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
