<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_email</name>
   <tag></tag>
   <elementGuidId>0584b261-d626-40f7-b564-f3ef62932389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79d09cd0-8206-4ef7-a71a-94a47ad59374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b10bd340-c32c-47e8-a93e-4981bafa2049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control1</value>
      <webElementGuid>9b60e286-e96d-4e2e-a511-60650e230919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_email</value>
      <webElementGuid>c68fc5e8-7d35-496e-91bd-eadfac1ee34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Resmi Penanggung Jawab Kegiatan</value>
      <webElementGuid>1ca312e4-1d9e-4c97-bb1d-6e1c18b88d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empjk</value>
      <webElementGuid>da0c9d05-9db4-4606-8c49-841579ff59c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empjk&quot;)</value>
      <webElementGuid>7ddd3cd5-8441-4cc4-a343-67f950410501</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empjk']</value>
      <webElementGuid>fa558311-0612-4552-9756-8aad1c13aca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[3]/div[3]/input</value>
      <webElementGuid>3ab0c332-3388-4668-89ad-8de40a6b48d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>16e1e2fd-e35a-4097-a0e5-b9cf1d2c6798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'pjkegiatan_email' and @placeholder = 'Masukkan Email Resmi Penanggung Jawab Kegiatan' and @id = 'empjk']</value>
      <webElementGuid>4005ecd2-e57a-4949-b624-6d85bd1c86ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
