<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_email</name>
   <tag></tag>
   <elementGuidId>106c1068-2244-459e-baf7-700cfc3263d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6424a461-038c-4fc9-8cb5-c25f04cbb799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emv</value>
      <webElementGuid>f239dfc2-4efa-4809-9d4d-6c1ec155b635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_email</value>
      <webElementGuid>b70e4f6f-3525-49aa-8cfe-cd0db1d872f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>bf985c5e-4b74-43b7-bfd8-936f191f574f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control3</value>
      <webElementGuid>c3ff6659-251a-4f05-a78b-b470732e94ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Pengembang Aplikasi</value>
      <webElementGuid>13830654-7473-4038-9b73-b7808a2ecaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emv&quot;)</value>
      <webElementGuid>82e7dfd1-9fa9-4da0-b394-3c3b001bdb11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emv']</value>
      <webElementGuid>088054c3-1a7d-4578-928b-769e029a86ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[5]/input</value>
      <webElementGuid>53c7cb20-830a-42cb-8298-79d125439c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div[5]/input</value>
      <webElementGuid>5bbf3ab7-50a6-41a3-a350-3bf961f18366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'emv' and @name = 'vendor_email' and @type = 'email' and @placeholder = 'Masukkan Email Pengembang Aplikasi']</value>
      <webElementGuid>f4d79ade-d923-472e-bc71-67949629fb2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
