<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjteknis_telp</name>
   <tag></tag>
   <elementGuidId>2a5752c3-4e49-436b-9eec-68029620b6d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nopjt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nopjt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7e2c7ed-0fa3-421d-8b2e-be128d02a269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjteknis_telp</value>
      <webElementGuid>53b9de5c-4d4c-476e-b93e-b95966b68684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b52c071c-1e87-4e09-bb2c-b30cbd293fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>281f0b8f-72c6-49cf-8db7-b972166910a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nopjt</value>
      <webElementGuid>e9c0114c-0218-4335-9cc8-b810045e2e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan No Telp/Hp Penanggung Jawab Teknis Aplikasi</value>
      <webElementGuid>0821756b-36c5-47b7-afc4-0f58942f3be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nopjt&quot;)</value>
      <webElementGuid>1e64a517-7f34-455e-8163-d264360a83d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nopjt']</value>
      <webElementGuid>08b148d2-dfb8-4be7-b950-85eb17c5fbc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div/div[4]/input</value>
      <webElementGuid>e065f107-59e6-4f5c-820f-ba143cf803ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>cbd1f82e-64e0-4ddf-acd8-1fec3e106b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pjteknis_telp' and @type = 'number' and @id = 'nopjt' and @placeholder = 'Masukkan No Telp/Hp Penanggung Jawab Teknis Aplikasi']</value>
      <webElementGuid>1491dd35-7148-4e1d-abfb-953a1706e3c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
