<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Silahkan Pilih Status Aplikasi--  _fee1a7</name>
   <tag></tag>
   <elementGuidId>63abd9f2-9b7f-424e-b129-fc3c975f5677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#statusApk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='statusApk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0b5a0e8a-de00-42e1-af95-b55fc2d90a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_aplikasi</value>
      <webElementGuid>4934bd44-f994-4972-8ded-04508437dff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>statusApk</value>
      <webElementGuid>dd5eeb0d-6209-437c-ad2b-914f15eee0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b907f1d8-76bb-4105-8c8e-c3981208fd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                               --Silahkan Pilih Status Aplikasi--
                               ON
                               OFF
                           </value>
      <webElementGuid>e9324e33-4a59-47db-874a-7c8ac8e3c6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;statusApk&quot;)</value>
      <webElementGuid>58299c41-5ceb-4eb3-b4af-12eddfcc3721</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='statusApk']</value>
      <webElementGuid>dbec2d87-f77a-4b8e-9e8b-086e009da3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div/div[5]/select</value>
      <webElementGuid>e733b9d6-29bb-4b7b-b5d0-ddb8c3b554e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>db832cd6-aba1-452a-a124-6bff741e2dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status_aplikasi' and @id = 'statusApk' and (text() = '
                               --Silahkan Pilih Status Aplikasi--
                               ON
                               OFF
                           ' or . = '
                               --Silahkan Pilih Status Aplikasi--
                               ON
                               OFF
                           ')]</value>
      <webElementGuid>edd16ee3-7a0e-4cc4-8cd8-c8b9b0ac0f1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
