<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih No Rekomendasi</name>
   <tag></tag>
   <elementGuidId>d05e59a3-d344-4e9a-8161-61551bf9fdab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.chosen-single > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='no_rek_chosen']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1447ae1-99bc-44b3-bddc-ff7dd00d7310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih No Rekomendasi</value>
      <webElementGuid>b73597a8-9c74-4031-ab24-ee86dfd6a5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_rek_chosen&quot;)/a[@class=&quot;chosen-single&quot;]/span[1]</value>
      <webElementGuid>c297a3d4-2201-446d-b6e2-0ff4f2f20f0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='no_rek_chosen']/a/span</value>
      <webElementGuid>2b83bdf1-3cdc-4e95-8a91-993250ba1637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/span</value>
      <webElementGuid>94bf4c9a-5f51-432e-bb74-11485eb7c913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pilih No Rekomendasi' or . = 'Pilih No Rekomendasi')]</value>
      <webElementGuid>22ac8add-47cb-4a5f-a6d7-11013c21a32e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
