<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya_1_2</name>
   <tag></tag>
   <elementGuidId>c1aea5ec-710c-4b99-ab56-830a32837568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='next3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f174754c-612d-445e-81f1-cf7a7717d4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btnNext pull-right next</value>
      <webElementGuid>e161aaa9-6aec-4370-bba9-503837e233cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next3</value>
      <webElementGuid>50316050-c04b-4c05-b09e-093bec100765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7e20161-aa7b-4e37-9bf2-c6565447329a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>8611c909-627c-4b5e-b2e6-2cb6aa3f447c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next3&quot;)</value>
      <webElementGuid>bf1badfb-e6b3-4dda-a221-ac0b3cb7d2ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='next3']</value>
      <webElementGuid>cef8b212-d78e-4139-afc9-40fef22ab27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[3]/button</value>
      <webElementGuid>052df0e4-1fbb-4924-b243-0483df011c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[3]/button</value>
      <webElementGuid>e6fd0ab1-66ca-45e7-b77a-0f986ceca0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'next3' and @type = 'button' and (text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>773d128b-27f0-421d-8840-dccf027ad730</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
