<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_email</name>
   <tag></tag>
   <elementGuidId>abf739ef-08b9-4587-af31-ccb1932f1624</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d476a42-c075-4a67-bae8-486ea8550cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emv</value>
      <webElementGuid>9cfa1854-d6ca-43fd-9551-7f114005fcb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_email</value>
      <webElementGuid>76c599ea-79c9-4886-9e90-62858e6d2531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>596a1d6e-e1f3-4c1b-9214-218506402f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control3</value>
      <webElementGuid>dd61e2c4-1023-4d0a-9ca0-758e181bd2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Pengembang Aplikasi</value>
      <webElementGuid>87e471a2-a019-4b81-b0e3-297a3dd69c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emv&quot;)</value>
      <webElementGuid>2cf0d9e6-ab99-4048-beba-abee66eff079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emv']</value>
      <webElementGuid>28926b43-877e-470e-a315-c5202303e149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[5]/input</value>
      <webElementGuid>4dcd54f3-e86d-4f93-b61d-4329492cb00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div[5]/input</value>
      <webElementGuid>d8f799a7-4927-40ff-9737-72577c23f051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'emv' and @name = 'vendor_email' and @type = 'email' and @placeholder = 'Masukkan Email Pengembang Aplikasi']</value>
      <webElementGuid>e28b398d-53b3-4ace-9ada-711269b8d5c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
