<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_email</name>
   <tag></tag>
   <elementGuidId>08aa5113-db09-4bdc-92e8-d505dc39b343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empjk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empjk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f99fdb6-9366-4c14-a5d7-63c0810ea74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b60c3976-2f54-44e0-9913-b284a67be26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control1</value>
      <webElementGuid>8013b8d0-4040-4b33-bfd9-1135c8afb392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_email</value>
      <webElementGuid>3ab6cb7c-78e4-482a-9437-c13505bca6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Resmi Penanggung Jawab Kegiatan</value>
      <webElementGuid>85e83a97-f859-4e8f-82d3-b4572e3fc434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empjk</value>
      <webElementGuid>6b32ca56-464f-4bb2-86ae-a6fa21a210ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empjk&quot;)</value>
      <webElementGuid>fa4e2c44-df9e-41a4-948e-4c10b3586ac4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empjk']</value>
      <webElementGuid>674fca39-5468-4fae-8bcd-4d42b3b7ba9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form2']/div/div[3]/div[3]/input</value>
      <webElementGuid>dd923c4d-7be1-47be-a0d6-d6db37900ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>c47ce8b3-b525-4075-b8ac-d67de8481739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'pjkegiatan_email' and @placeholder = 'Masukkan Email Resmi Penanggung Jawab Kegiatan' and @id = 'empjk']</value>
      <webElementGuid>ea69d53a-d8c0-4355-a033-b66e3c270a3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
