<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_port</name>
   <tag></tag>
   <elementGuidId>15c4fefb-b819-4e92-8919-b8ae1c7e2c62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#port</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='port']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5985d865-14af-4397-aee7-ebcd82cb4683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>858dd1e8-04ba-4a26-ade8-1c11a34e30a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>port</value>
      <webElementGuid>319a6f99-8f36-4cdc-9180-f66cb89eeabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>port</value>
      <webElementGuid>bd3447f6-e515-42fb-acff-3675e34218da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4e1733a7-c7e4-414b-9881-5c446afb4be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan port yang digunakan</value>
      <webElementGuid>e1d080b1-3793-40e1-8dac-f734a8aa3d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;port&quot;)</value>
      <webElementGuid>53f43671-6a13-4eff-8207-6abe6532a1c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='port']</value>
      <webElementGuid>89e39733-060f-49b3-b1b3-de170bb072b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[3]/input</value>
      <webElementGuid>1b9aad0f-6c46-4bd9-98f2-71119787adfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>336c8b75-e2e5-49e1-8b2a-dc853ce0d1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'port' and @id = 'port' and @placeholder = 'Masukkan port yang digunakan']</value>
      <webElementGuid>311ffa05-c399-4654-aefe-b7bc1576b4ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
