<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_username_db</name>
   <tag></tag>
   <elementGuidId>3c2df253-9ca1-4c3b-bb17-d1a6e0aa4550</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unameDB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unameDB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1124b0f6-768b-4c03-834b-5b0828c8b508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>923ab2dc-fe9a-4942-be42-36e6563b1114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_username_db</value>
      <webElementGuid>cff510b2-b9d1-422b-a7d6-b85dfe8c5ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>629e83eb-50f0-4ce0-9aef-cbd11b02afbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Username Database</value>
      <webElementGuid>76ac56d9-1660-49ee-9f18-ddfaeba63689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unameDB</value>
      <webElementGuid>f18f6351-2051-4f34-ad68-2a82f239b2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unameDB&quot;)</value>
      <webElementGuid>37270c45-3bfc-4ea9-8f4c-b29c9820c0ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unameDB']</value>
      <webElementGuid>b0baa9ba-a6cd-48cd-9943-46e1d9b40427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[7]/input</value>
      <webElementGuid>844389bf-cd33-4d41-a3a0-6e2c6f3a22b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>950f4e9d-26b0-4eb6-b915-1d6443800c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'adm_username_db' and @placeholder = 'Masukkan Administrator Username Database' and @id = 'unameDB']</value>
      <webElementGuid>99449bfc-c681-4a06-9643-f42975ae116c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
