<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_alamat</name>
   <tag></tag>
   <elementGuidId>a3b6fcbf-68a5-42e2-9d9c-a9199621d337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alamatv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alamatv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08b2116f-cd60-4dff-ad0d-63037a6f5ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_alamat</value>
      <webElementGuid>aee86f9d-2beb-4f42-bdda-f98723271874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db95b551-419d-4ff1-b3fe-e7a9ef38d093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eb39ff15-21df-441d-9250-7c62a0d9bce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Alamat Pengembang Aplikasi</value>
      <webElementGuid>50c57285-3dd2-4d13-91d1-8e16c1ba174c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alamatv</value>
      <webElementGuid>45519864-5fdc-4f75-9a6e-305de0f76784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alamatv&quot;)</value>
      <webElementGuid>d4f47a94-3383-4213-8a5a-c7517985a505</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='alamatv']</value>
      <webElementGuid>0c39a157-9aae-4a0b-b834-a2d8e93d9910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[2]/input</value>
      <webElementGuid>7b3033fa-94fd-42d7-8bf0-1bf14f314114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div[2]/input</value>
      <webElementGuid>b639859d-9e58-4e5f-be46-861a2034b240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_alamat' and @type = 'text' and @placeholder = 'Masukkan Alamat Pengembang Aplikasi' and @id = 'alamatv']</value>
      <webElementGuid>48fb3b1f-7645-4486-aad5-43985f713bbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
