<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_cp</name>
   <tag></tag>
   <elementGuidId>232db5b5-3ce7-4197-8d02-1ea7b4803016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cpv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cpv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b0b4bf1-7ceb-4096-b422-6cd7158da338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_cp</value>
      <webElementGuid>cb3c77d8-0272-4573-adac-ea0166150a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ff48e89-5feb-4e0c-872c-84062adbd26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9c1adc09-43dc-4f5e-adb2-b38ed852470d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan CP Pengembang Aplikasi</value>
      <webElementGuid>5e7b1616-6d2d-4598-93ee-d8f7294b4c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cpv</value>
      <webElementGuid>f4ba0ae8-5fb1-4df9-bafd-5ea098a2ef74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpv&quot;)</value>
      <webElementGuid>445e962d-e8fc-432a-8977-b4b665a1512b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cpv']</value>
      <webElementGuid>5ecc3614-fcb9-4d05-912b-436410cacae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[4]/input</value>
      <webElementGuid>e96c8e90-c96c-4939-a1a8-9d039869c540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/input</value>
      <webElementGuid>54355c98-3aa2-46a8-9d79-11cc142a4fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_cp' and @type = 'text' and @placeholder = 'Masukkan CP Pengembang Aplikasi' and @id = 'cpv']</value>
      <webElementGuid>dd3bae7f-b62c-48df-b747-869bbc45e380</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
