<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjteknis_telp</name>
   <tag></tag>
   <elementGuidId>18830b2d-83f6-480e-a562-15f4dcf117ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nopjt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nopjt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdaab728-6f5b-4c12-85ed-b3ab03ba080a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjteknis_telp</value>
      <webElementGuid>86046011-f9d9-444c-b18b-7e1fe672b5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>bfed9058-30e7-4972-bc75-5bd75007ae70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>78471b6b-00b8-483a-9f42-689c71aefb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nopjt</value>
      <webElementGuid>e37697fd-0474-480e-840e-3d70606dd0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan No Telp/Hp Penanggung Jawab Teknis Aplikasi</value>
      <webElementGuid>f91464ee-ba74-4ec9-9aa3-b5f28dc3874f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nopjt&quot;)</value>
      <webElementGuid>a586d5ad-11f5-4f82-92dd-b204c6f71249</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nopjt']</value>
      <webElementGuid>575bd06c-7c1f-4d31-8068-faf0e5693400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div/div[4]/input</value>
      <webElementGuid>e39a23c2-680e-40a2-ae96-f42131424e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>881b719d-f23e-424d-9230-05a57f0978c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pjteknis_telp' and @type = 'number' and @id = 'nopjt' and @placeholder = 'Masukkan No Telp/Hp Penanggung Jawab Teknis Aplikasi']</value>
      <webElementGuid>c679c228-1e3c-48f3-b96a-ad81e1f464a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
