<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_alamat_url</name>
   <tag></tag>
   <elementGuidId>c3309b87-e85a-484f-b403-3f6301cede11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#urlapk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='urlapk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b93c6fe-7284-47b6-acbc-9b377b8d7c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat_url</value>
      <webElementGuid>abd493d7-2166-496f-aaee-b174092d8b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5acfa607-01bb-4b7a-9c2c-ee4929aa6f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>28641cdf-ce80-4edf-a650-aed1ad2053ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Alamat URL</value>
      <webElementGuid>7d691ed1-c6f6-45b1-8798-2a40d7be0fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>urlapk</value>
      <webElementGuid>86e7c533-afb4-42c1-a23b-53ade8a2a540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;urlapk&quot;)</value>
      <webElementGuid>88b15327-fbc8-48ff-8dc3-a023fe69a687</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='urlapk']</value>
      <webElementGuid>eb2c0e26-89ca-40c6-b135-b1ac77bcdfb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div/div[2]/input</value>
      <webElementGuid>22d19a49-b939-4e31-a05b-10dc1303ebc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>bbb2e5d5-fdb4-4abe-a393-ccdc35518ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'alamat_url' and @type = 'text' and @placeholder = 'Masukkan Alamat URL' and @id = 'urlapk']</value>
      <webElementGuid>9d77c08e-bfc8-4ea4-a330-b8f1a5d95147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
