<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_password_db</name>
   <tag></tag>
   <elementGuidId>9ad34a5c-1935-4549-a7e4-56b1b38c3061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pwDB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pwDB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d31d6523-314d-4012-935c-fa479c2158d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bfa654ef-0f19-42f2-966e-ae37a65cb27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_password_db</value>
      <webElementGuid>198fbb14-bd17-455e-91fb-48e4b0eb3848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>461c5326-fade-4902-8346-6480132089b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Password Database</value>
      <webElementGuid>7687d1a6-1cac-44aa-b12d-73988b69397a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pwDB</value>
      <webElementGuid>eb85847a-9b70-4d2a-9816-9a923b7d9ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pwDB&quot;)</value>
      <webElementGuid>6cfa0b2c-d958-49c7-9517-01b82efceb07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pwDB']</value>
      <webElementGuid>1b646515-0933-4efc-9b83-eea63c7ab8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[8]/input</value>
      <webElementGuid>9c046540-9cd2-4c32-b18a-1db429404a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>3770fe56-5c58-49c1-9d25-b5f6c3f8cdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'adm_password_db' and @placeholder = 'Masukkan Administrator Password Database' and @id = 'pwDB']</value>
      <webElementGuid>cbbbe11c-28ac-4fd9-bf02-71e5f2b83fba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
