<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_password_aplikasi</name>
   <tag></tag>
   <elementGuidId>a8e38168-54a9-4ef4-8baa-ff439a9a20c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pwApk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pwApk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19521f33-f449-458f-b405-b191a49b1af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>535698c9-bc29-4e45-a9f0-4e02e33648a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_password_aplikasi</value>
      <webElementGuid>7150b544-4991-4d7c-9ff4-fe17cfb967bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>16bb7116-c2d5-4f74-948d-20df02763026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Password Aplikasi</value>
      <webElementGuid>a94cf01a-87f8-47be-868d-830619a85b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pwApk</value>
      <webElementGuid>15a659c7-dbb5-4d13-b768-9178cae17f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pwApk&quot;)</value>
      <webElementGuid>a7beee98-90d0-4844-8cb3-8fc7f2025049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pwApk']</value>
      <webElementGuid>49fb51b5-c201-4210-b38f-3fef7073c6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[6]/input</value>
      <webElementGuid>4a6d7b59-0541-4f14-ae07-61740801e153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/input</value>
      <webElementGuid>8c731591-4dd0-475e-ba0c-ae5fd5768f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'adm_password_aplikasi' and @placeholder = 'Masukkan Administrator Password Aplikasi' and @id = 'pwApk']</value>
      <webElementGuid>b04e7007-52da-4230-a577-896c9173b37f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
