<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_versi_bahasa</name>
   <tag></tag>
   <elementGuidId>094a22d0-a326-4aa3-a2b1-70ead3a4273d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;versi_bahasa&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='versi_bahasa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9d0cd00-dce4-4541-8bf5-6f541fc112fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>beba567d-d56f-464b-bdcd-e784978fedc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>versi_bahasa</value>
      <webElementGuid>0dc3f5b5-6246-4cb2-8930-75bad7ecbbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-3 col-sm-3 col-xs-3 form-control</value>
      <webElementGuid>8fdd9d8c-ec2a-4874-9569-dee7ff608c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Versi</value>
      <webElementGuid>627327b1-a396-4369-9a51-87e8f9f9afb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;col-md-3 col-sm-3 col-xs-3 form-control&quot;]</value>
      <webElementGuid>7c3f6d3b-1933-44fe-b9e8-f41e10b927b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='versi_bahasa']</value>
      <webElementGuid>6cb16be0-61ed-48f5-8a9e-c08de7efbc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[2]/input</value>
      <webElementGuid>7ab17a77-5ca5-4e74-9d64-1e2f58f0c1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>2a5e8c54-60e2-4a2b-bdf0-9c6948a11882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'versi_bahasa' and @placeholder = 'Versi']</value>
      <webElementGuid>89e9f42c-2b30-4561-92de-4364e82156d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
