<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjteknis_email</name>
   <tag></tag>
   <elementGuidId>9f683b18-b8bf-4e00-9580-5efd3eafc477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empjt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empjt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>757fd874-d3f4-4587-bc9f-aea75ab85fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjteknis_email</value>
      <webElementGuid>dbaca940-7717-4a7d-9e30-054bcf8cd0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>d40dc945-5bfb-4c70-8a24-75654b1bc9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control email-control2</value>
      <webElementGuid>0e0ebedb-8fdf-4819-8d87-3060b096213d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email Resmi Penanggung Jawab Teknis Aplikasi</value>
      <webElementGuid>797bfa2a-af09-427b-a7e1-ae54a82918c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empjt</value>
      <webElementGuid>ad1a9672-57e3-481f-86ae-d3aa78928f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empjt&quot;)</value>
      <webElementGuid>0812a8a2-e4d7-4f45-926e-b9f6c37d82dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empjt']</value>
      <webElementGuid>7fece7ff-c93a-4d39-9adb-b80ca120cf60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div/div[5]/input</value>
      <webElementGuid>00b81bbb-9197-4ad0-9717-b567832ef68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div[5]/input</value>
      <webElementGuid>aa224357-e69f-495f-80ae-026eafb76b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pjteknis_email' and @type = 'email' and @placeholder = 'Masukkan Email Resmi Penanggung Jawab Teknis Aplikasi' and @id = 'empjt']</value>
      <webElementGuid>a412dc36-a747-43e9-b6f2-ae24b52cabd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
