<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_adm_user_aplikasi</name>
   <tag></tag>
   <elementGuidId>488db003-fd35-4e20-9805-aba1d0b2d103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unameApk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unameApk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41f62859-74c8-4ea1-bf07-cada2f8fdab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b4c8495-43f1-4adf-808e-5ed5564aa041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adm_user_aplikasi</value>
      <webElementGuid>2d2a3d63-3b8a-45c3-9f2d-51dc500b8e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>49981610-bb1b-4834-ac8e-32694fe69f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Administrator Username Aplikasi</value>
      <webElementGuid>d189790a-b63b-4f04-b9bc-1b1eaccfdfe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unameApk</value>
      <webElementGuid>e47adb9b-6500-42e1-af1e-61fa49bbbf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unameApk&quot;)</value>
      <webElementGuid>9011fd54-a8b4-4370-aa60-383ab6eba757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unameApk']</value>
      <webElementGuid>f062ee70-8a5a-4d84-ab2c-5e050da6e97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div[2]/div[5]/input</value>
      <webElementGuid>74b4c657-b6da-49e4-8c78-7c5b25f19cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>a33ebf37-c059-4708-9f9c-ed63f5b8d34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'adm_user_aplikasi' and @placeholder = 'Masukkan Administrator Username Aplikasi' and @id = 'unameApk']</value>
      <webElementGuid>b0779974-2157-4c0b-abd3-c1f4893391b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
