<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nama_aplikasi</name>
   <tag></tag>
   <elementGuidId>aa737155-7a09-4cac-8d3d-9284d3ac388e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nmapk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nmapk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52bf5c6a-e8f4-44c9-bdfd-af56cd038355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_aplikasi</value>
      <webElementGuid>cc82ef6c-5029-446a-a8cc-94c3af4d028f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a7edf7bb-79b0-4d25-bf1c-6a3424242662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>5dcccde1-f7b0-4639-864c-e48d5f1a7c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Aplikasi</value>
      <webElementGuid>0c5c3734-ac8e-4399-a9d8-aedd55b1e5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nmapk</value>
      <webElementGuid>21f93a47-b052-420d-8d8a-80e2df52ed8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nmapk&quot;)</value>
      <webElementGuid>d644b053-36bf-462d-a802-f20665f52599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nmapk']</value>
      <webElementGuid>66332265-9b96-4904-a080-df92d07bbe3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div/div/input</value>
      <webElementGuid>a6754a67-85ac-4db1-95b6-b10e49340102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d406889f-e61b-41cc-a8be-210f64bf08a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_aplikasi' and @type = 'text' and @placeholder = 'Masukkan Nama Aplikasi' and @id = 'nmapk']</value>
      <webElementGuid>e96c5a34-358b-4661-b5ec-3e43382a7b3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
