<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor_telp</name>
   <tag></tag>
   <elementGuidId>e8866b0a-0c65-420f-8e1a-11ec45bd6ff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telpv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telpv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7df0968d-e677-4c74-af2b-f57ffc33ff7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_telp</value>
      <webElementGuid>bd81507d-fa81-452e-95e4-73d248a2efc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>144b5409-fe92-4279-bea8-90e1eccdf316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>98e07429-7da0-45e8-83c3-7a35a0a4b094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan No Telp/Hp Pengembang Aplikasi</value>
      <webElementGuid>fb5d7886-cfd2-4451-b971-79d86a8862b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telpv</value>
      <webElementGuid>1048ba58-78f9-470b-a789-99e2eb7870c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telpv&quot;)</value>
      <webElementGuid>f726a11e-7045-4375-a2fa-44624a73dbc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telpv']</value>
      <webElementGuid>6189630f-1474-4dfa-9083-67ed19126bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form3']/div/div[2]/div[3]/input</value>
      <webElementGuid>10f194c3-b3fb-4165-a9be-32912d0fe922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div[3]/input</value>
      <webElementGuid>092405ab-abcf-489b-a7ad-4882311b8086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'vendor_telp' and @type = 'number' and @placeholder = 'Masukkan No Telp/Hp Pengembang Aplikasi' and @id = 'telpv']</value>
      <webElementGuid>cadb938a-b80a-4c4b-ba1f-d4266ec87684</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
