<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Silahkan Pilih Status Aplikasi--  _fee1a7</name>
   <tag></tag>
   <elementGuidId>2d94c4f4-f883-41aa-8f16-89f07a0a325d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#statusApk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='statusApk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d12c592d-cb9b-45f2-bef2-1b362bfd1dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_aplikasi</value>
      <webElementGuid>0d233a9e-d085-48a9-9db7-e4d947e2c057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>statusApk</value>
      <webElementGuid>121945b9-d5b1-49aa-bc46-e9ec5116d7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>00bf5e9a-b830-4dc0-b861-b4ff3fdbc2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                               --Silahkan Pilih Status Aplikasi--
                               ON
                               OFF
                           </value>
      <webElementGuid>160a77f6-0e4c-4ce4-b303-08c1397b4d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;statusApk&quot;)</value>
      <webElementGuid>2461688c-9bf7-4a7b-8664-78855471e524</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='statusApk']</value>
      <webElementGuid>fe81b127-dfc2-462f-a982-afb80a7f2232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div/div[5]/select</value>
      <webElementGuid>1d9afb1c-e170-4851-91c3-3f9758bb233d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>c044429c-068e-4c31-a7d1-f826f0b8c31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status_aplikasi' and @id = 'statusApk' and (text() = '
                               --Silahkan Pilih Status Aplikasi--
                               ON
                               OFF
                           ' or . = '
                               --Silahkan Pilih Status Aplikasi--
                               ON
                               OFF
                           ')]</value>
      <webElementGuid>a21e65b9-0b92-4368-89c5-f90b1e146709</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
