<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_deskripsi_aplikasi</name>
   <tag></tag>
   <elementGuidId>7ee6bb4d-d49a-4d98-950d-a587fdb9faec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='desc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>aab5917c-60e8-4cf6-ae57-54c25b51283f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deskripsi_aplikasi</value>
      <webElementGuid>88a8777a-6090-4476-80f7-a82018fd370a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>6009db6f-507f-4f53-a72c-bac22dc5d253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>618fd559-e44c-465d-8c4d-ee02115bb1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>8789812b-d734-4d28-ab29-1157a8c05fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Deskripsikan Aplikasi Anda</value>
      <webElementGuid>865c3620-70b3-4bd9-927a-6fd31e44b949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>desc</value>
      <webElementGuid>265dc491-68fe-48f4-ada1-235ec0f9e822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desc&quot;)</value>
      <webElementGuid>afe5a513-f11d-4ca3-8d8e-ca49fe0cf266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='desc']</value>
      <webElementGuid>210132b6-ae60-4858-af71-b10432b6a03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form1']/div/div/div[4]/textarea</value>
      <webElementGuid>98c3504f-678f-4ae8-812b-842ac7ce8aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>62365714-51cd-4c1c-a814-6f1e2c6d9af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'deskripsi_aplikasi' and @placeholder = 'Deskripsikan Aplikasi Anda' and @id = 'desc']</value>
      <webElementGuid>2fc4b7f3-c3fa-4977-aa3a-77c418106786</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
