<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kriteria dan Ukuran Keberhasilan</name>
   <tag></tag>
   <elementGuidId>44629b4e-60d9-42fa-8073-b5a9d8fb00e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='permohonan_aplikasi']/div[2]/div[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27a9638b-6938-4a40-a775-5894b9cfc8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-group</value>
      <webElementGuid>6834e82a-4283-4f1c-bccd-82cafa597c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Kriteria dan Ukuran Keberhasilan
              </value>
      <webElementGuid>eb16fdff-709f-480f-b4f8-95c386019346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permohonan_aplikasi&quot;)/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]</value>
      <webElementGuid>83dd8ff3-25a1-400a-8515-a558fe505d5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permohonan_aplikasi']/div[2]/div[7]</value>
      <webElementGuid>4ef253d7-1531-4242-a6c4-a94a9a6f39c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]</value>
      <webElementGuid>f7ce55fd-5327-43b0-be38-321b80b7a001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                Kriteria dan Ukuran Keberhasilan
              ' or . = '
                Kriteria dan Ukuran Keberhasilan
              ')]</value>
      <webElementGuid>1f990594-c4d4-428c-a93b-ccc06c84566e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
