<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tgl_mulai</name>
   <tag></tag>
   <elementGuidId>3da1f85e-78e5-433b-ba70-0417bb8e6940</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tgl_mulai']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tgl_mulai&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed4aa2a0-de71-479d-9991-b183628d44bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>299126fb-cecb-41c0-a98f-88d65ac6f0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-control</value>
      <webElementGuid>92d6c00d-9d9f-4cd3-ac3e-2f335e2048fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_mulai</value>
      <webElementGuid>5251a2ad-d96e-49a2-ae15-a590b9f3e57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tanggal Mulai</value>
      <webElementGuid>6b4283f6-08b7-4e54-873a-61e2493df0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4013954f-c2e7-4444-a096-4453b0c22cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker&quot;)/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>7a82fc0a-8895-4934-b3f1-10f99144c234</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tgl_mulai']</value>
      <webElementGuid>fdc13c13-4e2b-4776-9d01-ff7626fc2d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepicker']/input</value>
      <webElementGuid>c34c0005-0b05-4a13-900a-22dd488f6542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/input</value>
      <webElementGuid>02ead8aa-a2fd-47ab-ad7a-57f139281f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tgl_mulai' and @placeholder = 'Tanggal Mulai']</value>
      <webElementGuid>800dfeac-dd83-4e6a-a8d3-59d2ff4a1b8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
