<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_jenis_aplikasi1</name>
   <tag></tag>
   <elementGuidId>c39541dd-0c2d-4a3a-a0d2-bd2155c1cfe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='jenis_aplikasi1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;jenis_aplikasi1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d367888-1df4-4b9b-8d71-0e5192685588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f48761ef-6226-40c0-8b96-6e5d1633b877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenis_aplikasi1</value>
      <webElementGuid>01f4b760-75f7-43af-a995-4c1ffdbfcd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Web Base</value>
      <webElementGuid>1f6cf3fd-0a3d-4450-9db5-8d5972e22e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permohonan_aplikasi&quot;)/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/input[1]</value>
      <webElementGuid>7b99d0fe-5d6f-492d-9c11-4e5522c9cff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='jenis_aplikasi1']</value>
      <webElementGuid>19e1c796-23e1-4180-bd0f-07f18fcd4601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permohonan_aplikasi']/div[3]/div/input</value>
      <webElementGuid>2c336d0e-4163-4839-b894-f256a548a83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>7a5ab82f-152a-4182-87af-fa9156314050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'jenis_aplikasi1']</value>
      <webElementGuid>e34c451d-34c6-4245-931d-c48dc33a59d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
