<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tgl_akhir</name>
   <tag></tag>
   <elementGuidId>010b4d1b-ffb9-4942-87fc-072dcc812e00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tgl_akhir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tgl_akhir&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2efa2373-85f5-407b-b325-62b17cb1ade9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a70ea232-ed2b-45c2-b7fe-76e71386b0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-control</value>
      <webElementGuid>32632c57-f84e-4574-bdbd-2d30633f8b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_akhir</value>
      <webElementGuid>cdc55d5a-85c1-488c-97eb-ac0ca4f30ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tanggal Akhir</value>
      <webElementGuid>4130ee50-87f6-425a-b542-c6c9f103c021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f5ff648-4cb3-4dfc-bba6-c88ed388661e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker&quot;)/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>33c71ec5-348f-4484-9eae-89d5c39654d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tgl_akhir']</value>
      <webElementGuid>25b77c3c-ace2-43b8-a44c-d07695ea4fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepicker']/input[2]</value>
      <webElementGuid>a37edbfe-68e4-42e4-8b9f-8ad939c9e598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/input[2]</value>
      <webElementGuid>86ae91a8-62d8-4dfa-a3ac-bb59536cfcdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tgl_akhir' and @placeholder = 'Tanggal Akhir']</value>
      <webElementGuid>5832c1f7-b451-467b-90b4-fe6d12ed2417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
