<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pjkegiatan_jabatan</name>
   <tag></tag>
   <elementGuidId>f61651ff-b73c-469f-9ec2-cd70a71f0438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pjkegiatan_jabatan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pjkegiatan_jabatan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cbcb059-adf3-4ac6-9e79-0c0b024f3d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f47aa000-d94f-41f0-90eb-d4a1a4c18f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pjkegiatan_jabatan</value>
      <webElementGuid>de6a8e2d-455b-4cf1-94c9-4d8eceae4af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ad44fb79-0beb-491b-ae21-587c96076f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isikan Jabatan penanggung jawab kegiatan</value>
      <webElementGuid>9f04722c-40aa-44a4-a72f-af139f953889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ecaa54ef-2eb4-4760-bde5-97f96196a7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;umum&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>db6b724b-be45-496a-b6ce-8851d908c3a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pjkegiatan_jabatan']</value>
      <webElementGuid>ff8ba4a1-b7c6-4301-aa41-6d4943128b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/div/div[3]/div/input</value>
      <webElementGuid>97a6eaa1-dcc2-4870-89b1-c938123ea426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>4e4b0bbe-c775-46c3-b0e3-a66eb06f60fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pjkegiatan_jabatan' and @placeholder = 'Isikan Jabatan penanggung jawab kegiatan']</value>
      <webElementGuid>a2575edb-1db6-4fba-a9c5-f3ccd2c92273</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
