<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Baru                  Pengembangan  _55895e</name>
   <tag></tag>
   <elementGuidId>28c83c08-f9d2-4adf-9f43-accbe66daf13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='apl_pengembang']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#apl_pengembang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>72ed0eb8-0686-4f3f-aae2-387b75d5a66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_pekerjaan</value>
      <webElementGuid>b18f70ea-6bd2-4633-a598-f55e6030b884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apl_pengembang</value>
      <webElementGuid>a4761c83-f944-4be3-91da-e815d35cf026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>920827b4-3e0b-4a86-b665-eed3764e581d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d3b35f4-b48b-4529-af19-655e213499de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Baru
                  Pengembangan
                  Berbagi Pakai
                </value>
      <webElementGuid>145f5690-05a7-49b9-8ce2-2ced0ce220ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apl_pengembang&quot;)</value>
      <webElementGuid>0e0a332d-5bcc-4f1a-8588-3e83c9db7300</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='apl_pengembang']</value>
      <webElementGuid>b145b938-584e-4b3c-81df-4b5bcaa08fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permohonan_aplikasi']/div[2]/div[9]/select</value>
      <webElementGuid>39d33909-3a45-4233-ad1a-27e7ea915633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/select</value>
      <webElementGuid>fa93f0ba-d1a6-4429-bfb8-78a05a906dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status_pekerjaan' and @id = 'apl_pengembang' and (text() = '
                  Baru
                  Pengembangan
                  Berbagi Pakai
                ' or . = '
                  Baru
                  Pengembangan
                  Berbagi Pakai
                ')]</value>
      <webElementGuid>7885a2fe-b351-423a-8cda-2630d4c82ce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
