<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please enter a valid number</name>
   <tag></tag>
   <elementGuidId>415c2383-517c-4b63-9c0c-eb6a523757d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nip_pjkegiatan-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='nip_pjkegiatan-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>669981d1-1b96-4c71-ae77-b76a0ff85c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nip_pjkegiatan-error</value>
      <webElementGuid>252117e6-6149-4423-8329-fcc857deba37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>dcb5d0cf-c156-4eb4-91c6-329d895b6449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>nip_pjkegiatan</value>
      <webElementGuid>81bbf4ae-fc95-4ce5-a140-aaa856c5919d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter a valid number.</value>
      <webElementGuid>ad017914-f529-4e60-9c4a-e50335970527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nip_pjkegiatan-error&quot;)</value>
      <webElementGuid>da3cffe4-3684-4f23-8a0e-3f01a8cf03e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='nip_pjkegiatan-error']</value>
      <webElementGuid>ab3cd09a-bec0-4a17-b3c3-f789c0920ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[5]/div/div[2]/label[2]</value>
      <webElementGuid>c09e9003-9268-4e89-a9d5-7dc58a068e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>561f0819-b82c-4b6c-9e6f-6810818d17d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'nip_pjkegiatan-error' and (text() = 'Please enter a valid number.' or . = 'Please enter a valid number.')]</value>
      <webElementGuid>2f611d79-b145-4733-8f7c-ad1033fc489d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
