<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_This field is required</name>
   <tag></tag>
   <elementGuidId>a2c12f71-f4c7-465b-9eea-3648b52f4712</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hjabatan_pj-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='hjabatan_pj-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>47211dce-ba5c-4243-9869-f4555a1dcfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hjabatan_pj-error</value>
      <webElementGuid>c160f4dc-ffeb-4e88-a08a-f5b177d09bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>c418790f-c965-4f6f-b557-039ecd2a613c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>hjabatan_pj</value>
      <webElementGuid>27b80305-b6d2-4b90-867a-7ae72ce78fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>35e4cc5a-ff9d-444d-b8bf-986239c1d225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hjabatan_pj-error&quot;)</value>
      <webElementGuid>7739d406-022b-414c-9436-4ed6fb8887ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='hjabatan_pj-error']</value>
      <webElementGuid>4f0aa84d-4ea8-465b-aa00-1cffd8e56ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[5]/div[2]/div[3]/label[2]</value>
      <webElementGuid>d1ab20b4-d75c-4755-b92f-29707b576dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label[2]</value>
      <webElementGuid>75148d4e-8c4e-46dd-a7d1-accb7662e08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'hjabatan_pj-error' and (text() = 'This field is required.' or . = 'This field is required.')]</value>
      <webElementGuid>53b10746-8f3d-4492-8a80-0897e2eb1351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
